### ISSUE TITLE
Incompatability with Terralith

### ISSUE THREAD

**Issue by HoneyClem** [Noaaan/MythicMetals#101]
My server crashes every time someone goes into an emerald peak from terralith

**Comment by Noaaan** [comment]
Which version of the mod are you using? 
If you still are on 1.18 this should already be fixed as of 0.14.3.
If you are on 1.19, then you will have to wait a bit longer as I am wrapping up the next release for 1.19 this weekend, which should include the same fix.

**Comment by HoneyClem** [comment]
I'm using 1.19, thanks for letting me know

**Comment by Noaaan** [comment]
Released as of the latest versions.

**Comment by Sunconure11** [comment]
I think this is back, in a sense.

https://pastebin.com/x2cW8iBB

**Comment by Sunconure11** [comment]
Also ran into this. @Noaaan 

https://pastebin.com/bVLTwiG8

**Comment by Noaaan** [comment]
If you are experiencing a feature order cycle, please open a new issue.
