### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by User3615** [Noaaan/MythicMetals#103]
Background: Fabric mods loader + some mods.
Conflict: Croptopia-1.19.2-FABRIC-2.0.8 & mythicmetals-0.15.3
Crafting table: action: making 'flour' from cereal like 'oats' or 'corn'. Made 'flour', took it and got one 'osmium ingot'.

**Comment by Noaaan** [comment]
This is probably related to recipes being broken due to broken tags. I am working on a hotfix that will release today

**Comment by Noaaan** [comment]
Fixed in the latest hotfixes

**Comment by User3615** [comment]
Thanks
