### ISSUE TITLE
Ticking Player/doubleXP Tag Crash

### ISSUE THREAD

**Issue by Bullseye55** [Noaaan/MythicMetals#104]
Currently in the nether, and died to either lava or a magma block, and cannot respawn/rejoin a singleplayer world. Mythic Metals is throwing an exception with its name(and a doubleXP tag null-by-missing-designator "attacker") attached. Log is attached for reference. Minecraft version 1.19, using the latest 1.19 Mythic Metals 0.15.2 Hotfix. I'm unsure if this is related to the other issue at the time of posting.

[latest.log](https://github.com/Noaaan/MythicMetals/files/9366236/latest.log)

**Comment by Noaaan** [comment]
I am concerned of your log with 500+ mods, it was very hard to read.
But you are correct. This seems like an oversight, will fix it tomorrow.

**Comment by Bullseye55** [comment]
Tend to be rather good with troubleshooting, and don't mind doing it most times. Custom-built pack, so, lot of effort....and a lot of bugs to fix and incompatibilities to go through. 1.19.1+ complicated things, too: always have to look at specifics.
Why I included the keywords so the log could be Control-F searched through.

Appreciated, and happy to help find it! :)
