### ISSUE TITLE
no bronze recipe

### ISSUE THREAD

**Issue by Sinogard** [Noaaan/MythicMetals#105]
im trying to make bronze in 1.19.2  and i cant find the recipe. Am I missing a setting?

**Comment by Noaaan** [comment]
Bronze is made in an Alloy Forge from Alloy Forgery. Bronze needs two pieces of copper ore and one piece of tin ore in order to be alloyed.

**Comment by Sinogard** [comment]
The recipe for both tin and bronze are not working in either ore or bar forms for the alloy forge.

**Comment by Noaaan** [comment]
This is actually an issue with Alloy Forgery, as common recipes (bronze, brass, steel, etc.) was moved there. It looks like the version which includes the recipes has not been released yet. 
I will make sure it is released soon.
