### ISSUE TITLE
Not able to join a server

### ISSUE THREAD

**Issue by SilverEYES05** [Noaaan/MythicMetals#111]
I was trying to join a server in 1.19 with the latest fabric version. I can play the modpack created in singleplayer but not able to join a server. This is the error code I keep getting.
![image](https://user-images.githubusercontent.com/112325053/187073833-f26a999f-5898-43c6-bd68-4479f3549d64.png)
[owo] handshake failure controllers with mismatched haches: mythicmetals:particles

**Comment by Noaaan** [comment]
https://docs.wispforest.io/faq/#i-get-disconnected-due-to-a-oo-handshake-failure-incompatible-server-when-trying-to-join-a-server

**Comment by BasiqueEvangelist** [comment]
Are you sure that you're using the same version of the mod on the server and the client? I can't see any other reason why hashes would be broken

**Comment by SilverEYES05** [comment]
I installed what I was told to and it’s the same stuff as the others were using. I even tried using a bit older versions since it recently got updated and also tried the beta version but nothing worked and I get the same error

**Comment by Noaaan** [comment]
Are you sure you are using the same version of Mythic Metals and owo-lib on the server?

**Comment by TripleDAK** [comment]
Looks like OWO is only updated to 1.18.2 causing dependency errors for Mythic metals.

**Comment by BasiqueEvangelist** [comment]
> Looks like OWO is only updated to 1.18.2 causing dependency errors for Mythic metals.

[What do you mean?](https://modrinth.com/mod/owo-lib/version/0.7.3+1.19)

**Comment by TripleDAK** [comment]
The only version for owo that is compatible with Mythic that I found is version 1.18.2. If this is not the case I would greatly like to find the updated files.

**Comment by TripleDAK** [comment]
NVM I found it. I had to download a different modpack that had the updated version and copy it and install it on my other modpack.
