### ISSUE TITLE
Crash at start-up

### ISSUE THREAD

**Issue by Profkamil007** [Noaaan/MythicMetals#113]
Hello! Your mod crashes at the start-up. Here is the crash report:
[crash-2022-09-11_12.52.34-server.txt](https://github.com/Noaaan/MythicMetals/files/9542335/crash-2022-09-11_12.52.34-server.txt)

**Comment by Noaaan** [comment]
This crash is caused by IndustrialTNT since they directly modify all TNT blocks

**Comment by Profkamil007** [comment]
Thanks for information. After removing the abovementioned mod, the game can be started without any problem.
