### ISSUE TITLE
[1.18.2 - v0.14.4] Hallowed Sword of Aegis allows smite 9

### ISSUE THREAD

**Issue by itsdinkd** [Noaaan/MythicMetals#115]
Some how some way you can enchant sword of aegis up to smite 9 even when limiting enchantments to vanilla limits. this is occurring in Another Quality Modpack 2 v1.6 

There is a enchantment limit set in my modpack.  No other weapon or tools can you bypass the max enchantment level except for aegis apparently.

**Comment by Noaaan** [comment]
This is intentional behaviour from the sword
