### ISSUE TITLE
Client Crash on Startup (0.16.0)

### ISSUE THREAD

**Issue by BosterJowls** [Noaaan/MythicMetals#117]
Getting a crash on startup,

hereto attached is the crash report.
[crash-2022-10-03_04.42.01-client.txt](https://github.com/Noaaan/MythicMetals/files/9693561/crash-2022-10-03_04.42.01-client.txt)

**Comment by Noaaan** [comment]
Could you test this build once it is ready? https://github.com/Noaaan/MythicMetals/actions/runs/3172118560
It moves the model handling code, since previously it was present on both server and client code, when it should only be present on client.

**Comment by BosterJowls** [comment]
How do I do that? sorry for being ignorant.

**Comment by Noaaan** [comment]
You might not need to, as I managed to re-produce it. It still does not work

**Comment by Noaaan** [comment]
Just pushed another change that did fix the issue on my end. 

When downloading from actions you simply download the artifacts (which contains the new mod jar) once they are finished being made. In this case you want this artifact: https://github.com/Noaaan/MythicMetals/actions/runs/3172505765

![image](https://user-images.githubusercontent.com/4163353/193528399-b7717e76-9d62-4157-8232-9d9d410e85f2.png)

**Comment by BosterJowls** [comment]
Thank you, trying it now :)

**Comment by BosterJowls** [comment]
Yo, it didn't crash anymore and got to the point where I created a world :)
