### ISSUE TITLE
Minecraft 1.19.2 - Crash when activating Mythic Metals V0.16.1 Update: found error, incompatible with Medieval Weapons

### ISSUE THREAD

**Issue by SirFreddo** [Noaaan/MythicMetals#122]
Hello, sorry to be of inconvenience, game is crashing only when i activate Mythic Metals, might be an incompatibility but i don't really understand the crash report: https://paste.ee/p/c4gEe 
I'd be glad to understand what is happening and why, thanks

**Comment by Noaaan** [comment]
This is known, and I did PR a fix for it that has been merged. It will likely be available in a future release of Medieval Weapons 
https://github.com/Globox1997/MedievalWeapons/pull/82
