### ISSUE TITLE
Searching quadrillium crashes the game

### ISSUE THREAD

**Issue by QTPieMuffet** [Noaaan/MythicMetals#124]
Issue with the current fabric release for 1.19.2 with the mod

[crash-2022-10-07_12.47.52-client.txt](https://github.com/Noaaan/MythicMetals/files/9730747/crash-2022-10-07_12.47.52-client.txt)

**Comment by Noaaan** [comment]
I believe that this is a incompatability with Facility.
Facility includes Frex, a library that Canvas uses for rendering. 
Mythic Metals includes Canvas support when using the Lumi Lights shaderpack, but it seems that it is unconditionally loading, causing a crash if it is not present.
Will look further into the issue.

**Comment by Noaaan** [comment]
Yeah, going over it the Lumi Lights compatability is severely out of date. 
It breaks if FREX is present and you are not using Canvas + Lumi Lights. 
I might make a resource pack or something for this at a later date, but for now I am just going to remove it from the mod.
