### ISSUE TITLE
For the love of god change the name of the Legendary Bang advancement

### ISSUE THREAD

**Issue by Hedwig7s** [Noaaan/MythicMetals#125]
Do you have any idea how much explaining I had to do to my friends after getting that?

**Comment by BasiqueEvangelist** [comment]
send proof

**Comment by Noaaan** [comment]
Personally I don't see this as an issue

**Comment by Noaaan** [comment]
https://monsterhunterworld.wiki.fextralife.com/Legendary+Bang
