### ISSUE TITLE
Recipe for steel using iron ore missing.

### ISSUE THREAD

**Issue by Mahadbaloch** [Noaaan/MythicMetals#126]
The recipe for steel using ores has a manganese ore with a yellow slot next to it indicating it would be iron ore, but nothing is there and the uses for iron ore does not show use in making steel. Recipe seems to be broken.

**Comment by Noaaan** [comment]
I am assuming you are using latest Mythic Metals for 1.19.2?

**Comment by Mahadbaloch** [comment]
Latest for 1.19

**Comment by Noaaan** [comment]
Thanks for opening this issue. This went under the rug after migrating most of the common forging recipes to Alloy Forgery.
I have fixed it and it scheduled for next release.
