### ISSUE TITLE
Silver and osmium ore is not very useful

### ISSUE THREAD

**Issue by Mahadbaloch** [Noaaan/MythicMetals#127]
Silver appears to be harder to get than iron, not considering that the new iron veins spawn with tons of iron you can get almost immediately in early game, but iron completely outclasses silver. After getting anything above copper armor the only use silver has remaining is beacon bases. Could there be a special use for silver added? Maybe the armor could have resistance to negative effects. 

Osmium also has a similar issue, being a pre-diamond metal that cannot mine obsidian e.t.c, exchanging protection for KB resistance compared to diamond. Osmium can be quit difficult to get a lot of, and grinding for it just to get armor worse than iron is a lot of effort for KB resistance. Perhaps an osmium alloy?

**Comment by Noaaan** [comment]
I do see your perspective here, and I do want to comment on this.  

Currently I do not plan to add any effects or tools to Silver. RIght now it simply exists for the purpose of providing a metal for Mythic Metals Decorations to create stuff with, E.G. chests, chains, and a upcoming metal + armor set re-color in the next release. If Silver did not facilitate this purpose, it would likely already have been removed from MM entirely.
I do have a few ideas on where to use it later, but currently I don't plan re-designing it, and it I will not prioritize it.

Osmium is a bit more challenging to work on, but currently it is very intentionally designed. 
Making Osmium stronger in its current state would probably bee too much. Giving it mining level 3 (same as a diamond pickaxe) previously proved to be a bit too strong, and such it was dialed back. I will re-consider whether or not this is the right choice.
When it comes to the armor values, it is intentionally set to match up with chainmail. This is such that with other mods, such as Origins, you are able to reap the benefits of its attributes (KB resistance, toughness) despite being restricted in what armor you can wear. 
Incentivizing Osmium by making alloys out of it is not the best solution, as requiring the player to always visit a specific biome to get the components for it is not always fun. I don't want to add it to any of the current alloys, and I do not believe I wish to create a new alloy just to give it another use.

**Comment by Mahadbaloch** [comment]
I see. That's fine.
Adventuring to highlands to find osmium is fun though

**Comment by Noaaan** [comment]
I have deliberated on Silver doing something in regards to negative effects. Nice nod to actual silver properties. Might write that down for later use. 

For Osmium I am not sure where to go with it, but in the air is an idea around some Osmium plating to improve the set maybe. Time will tell.
Unless you want to discuss this further, I will close this for now.
Thanks for sharing your thoughts with me!
