### ISSUE TITLE
Celestium Can be made without Carmot

### ISSUE THREAD

**Issue by DJSwamp** [Noaaan/MythicMetals#130]
I may get overly wordy, don't really know how to do these. Just pointing out a potential error in coding/recipes, when making Celestium Ingots in an Alloy Forge. In essence, you can use Star Platinum, Kyber, and Unobtainium ingots to forge Celestium without Carmot. 
Generally you require Starrite, Platinum(or their alloy Star Platinum), Carmot, Kyber, and Unobtainium to forge Celestium, either in raw, ore, or ingot form. 
However, if crafting with the Ingot Recipe, and specifically using the Star Platinum Alloy version, Carmot is not included in the recipe. This does not seem to be an intended recipe, as other recipes using alloys tend to just replace any alloy's involved ingredients, not remove others from it. 

This recipe can be checked in REI and easily confirmed in game.

**Comment by Noaaan** [comment]
Which version of the mod are you using? I believe this is fixed in the latest releases

**Comment by DJSwamp** [comment]
Oh jeez, I am going to have egg on my face if this is a "Wrong Version" issue. Lemme check

**Comment by DJSwamp** [comment]
Yeah, this one's on me, my bad. I wasn't aware the server this modpack is linked with didn't have the most recent updates. Feel free to close this.
