### ISSUE TITLE
Latest Mythic Metals crashes with this mod

### ISSUE THREAD

**Issue by StockiesLad** [Noaaan/MythicMetals#133]
1.18.2
[latest.log](https://github.com/Noaaan/MythicMetalsDecorations/files/9999339/latest.log)

**Comment by Noaaan** [comment]
This issue is known, and is related to the 1.18.2 version of Incubus Core
I have already made a pull request backporting the fix for this, which you can see here: https://github.com/devs-immortal/Incubus-Core/pull/23

**Comment by StockiesLad** [comment]
ah ok, I downloaded the PR.
