### ISSUE TITLE
The stack 0 air was in a state of being empty and not being empty, report this!

### ISSUE THREAD

**Issue by ereese99** [Noaaan/MythicMetals#138]
Got that error just running through my server. A spider was stuck in a block caused by mythic metals.

[message.txt](https://github.com/Noaaan/MythicMetals/files/10357493/message.txt)

**Comment by Noaaan** [comment]
See #94 for more context.
As of latest Mythic Metals in development (0.17.0), this will no longer directly crash your game, although this error is still scary, and can crash in other contexts.
