### ISSUE TITLE
Runite Carmot Staff disconnects players

### ISSUE THREAD

**Issue by LopyLuna** [Noaaan/MythicMetals#140]
Runite Carmot Staff forces players to be disconnected on server when used

**Comment by Noaaan** [comment]
Which version of Mythic Metals are you using? An issue like this was fixed in 0.16.4

**Comment by LopyLuna** [comment]
sorry for the late response the version is 0.15.5+1.19

**Comment by Noaaan** [comment]
This crash has already been fixed in latest Mythic Metals. Please upgrade from 1.19 to 1.19.2, as I no longer support it.
