### ISSUE TITLE
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mythicmetals'!

### ISSUE THREAD

**Issue by Valorioo** [Noaaan/MythicMetals#143]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mythicmetals'!

Here is the crash log
[crash-2023-01-30_20.13.19-client.txt](https://github.com/Noaaan/MythicMetals/files/10542010/crash-2023-01-30_20.13.19-client.txt)

**Comment by Noaaan** [comment]
The alpha version of Mythic Metals requires the latest version of owo-lib. I have already bumped the version in the fabric.mod.json, so you are notified of this for the actual release.
