### ISSUE TITLE
Palladium Armor enchanted with Fire 4 Protection gives infinite stacking yellow hearts while standing in lava

### ISSUE THREAD

**Issue by EvionFox** [Noaaan/MythicMetals#145]
So, this is a weird one - on a dedicated server, we've found that wearing a set of Palladium armor with Fire Protection 4 enchants on it causes the player to gain yellow hearts over time as they take ticks of "damage" while standing in lava.

Minecraft Version: 1.19.2
Fabric API 0.73.2

This occurred on both Mythic Metals 0.16.4 and the new 0.17.0

I checked the logs and there's nothing client side or server side noting an error when this happens.
![huge_2023-02-03_13 24 09](https://user-images.githubusercontent.com/119480493/216693280-70a1e8bf-6a11-4394-b575-a9c30ec223b4.png)

Upon further testing, the results:
Fire Prot 4 enchants:
Only 1 piece of palladium armor - take damage, lose hearts
2 pieces - neutral damage, get the damage tick animation, but no heart loss
3 pieces - slow yellow heart increase with each tick
4 pieces - faster yellow heart increase with ticks

Fire Prot 3 enchants:
1 and 2: take damage
3 armor pieces: Neutral damage, just animation
4 armor set: Slow increase of yellow hearts over time.

I assume it's some combination of the math between the Palladium armor's resist and the enchant causing negative damage to the player.

Here's our modpack mod list to help:
[modlist.txt](https://github.com/Noaaan/MythicMetals/files/10582299/modlist.txt)

**Comment by Noaaan** [comment]
Well this would definitely be a mod compat problem, as I have never heard of any enchants that grant absorption on fire damage. Could you find out what enchant it is/where its from?

**Comment by EvionFox** [comment]
I was extremely confused too, as it's just the vanilla Fire Protection enchantment from Minecraft, not an absorption power.

But after a lot of trial-and error, I found the culprit mod: No Enchant Cap https://www.curseforge.com/minecraft/mc-mods/no-enchant-cap

And tested it - it's an issue on their part, not on Mythic Metal's side, as the same effect also happens with Netherite Armor with the full Fire Protection enchantment. Sorry for the trouble - I'll go submit the issue on their side!

**Comment by Noaaan** [comment]
W- they actually reduce the damage so much it *heals* you?
This is based.
