### ISSUE TITLE
1.19.3 - Ores not spawning correctly?

### ISSUE THREAD

**Issue by Noaaan** [Noaaan/MythicMetals#146]
There might be some issues with worldgen not correctly applying. This need further investigation.

**Comment by drakosoldier298** [comment]
Was just about to open an issue for this to move it out of discord, im daedreus.
affected mods.
mythic metal;s 0.17.0 1.19.3
tech reborn 5.5.0
was asked to run /place feature while underground, doesnt seem to do anything 
![image](https://user-images.githubusercontent.com/30358222/216746029-3d9ca7a6-02db-4ea1-a7eb-33ebdeded1d3.png)

Banglum fails entirely
Adamantites the only thing that doesnt reply with "failed to place feature"

**Comment by Rogenar** [comment]
I tried Fabric 0.17.0 1.19.3 version, I faced the same situation. Ores are not formed. Will this be fixed with the next update?

**Comment by Merith-TK** [comment]
Fabric API is to blame

0.73.3 added some world gen helpers, but appearntly forgot to mention them in the release changelogs

Ore generation works just fine on 0.73.0

**Comment by Noaaan** [comment]
Fixed in 0.17.1+1.19.3
