### ISSUE TITLE
Weird crash with a NullPointerException on a "null attacker"

### ISSUE THREAD

**Issue by nixord** [Noaaan/MythicMetals#147]
Heres the whole console log with the crash log as well: https://paste.ee/p/9W7ry
Im in the nether and apparently somewhere a mob or something has a Carmot Staff and its making that error.
Now I cant even enter the world cause the mob is still trying to attack me (Im assuming its a random zpiglin)

**Comment by Noaaan** [comment]
Duplicate of #142. Update to the latest official release of 0.17.0

**Comment by nixord** [comment]
Oh... Sorry, I didnt see it. Thank you very much <3
