### ISSUE TITLE
[Suggestion 1.19.2] Config for Fire Resistence

### ISSUE THREAD

**Issue by itsdinkd** [Noaaan/MythicMetals#148]
quickly checking update for 17.x and saw palladium reworked. Does this add fire resistance? if so, can you add a config (if not already) on removing this effect? Fire Res is not available in my modpack since tons of custom mobs and bosses use fire damage

**Comment by Noaaan** [comment]
The armor only implements fire *protection*. It does not introduce Fire Resistance in any way

**Comment by itsdinkd** [comment]
> The armor only implements fire _protection_. It does not introduce Fire Resistance in any way

Ah. got it, thanks.
