### ISSUE TITLE
[1.19.2 Bug] Blacklist not Respected

### ISSUE THREAD

**Issue by itsdinkd** [Noaaan/MythicMetals#149]
![image](https://user-images.githubusercontent.com/35115304/218282910-2a56e017-623e-4c57-9fac-eaeb08642a4c.png)

Config has aqm2:mining_dimension in the blacklist however it seems that it is still generating MM ores in the dimension.

![image](https://user-images.githubusercontent.com/35115304/218282927-a05873d1-44d4-42ab-8a45-49c40c83aa14.png)

**Comment by Noaaan** [comment]
Did you get it working or find an alternative?

**Comment by itsdinkd** [comment]
I thought I changed the dimension name as I was using own datapack for the mining dim but apparently the dimension name was the original still. user error on my end

**Comment by itsdinkd** [comment]
Hey sorry, gotta reopen. i was wrong. i put the dimension in and it did not blacklist

![image](https://user-images.githubusercontent.com/35115304/227740544-99e7d8ed-8dc1-459e-b559-9ebee5f1c832.png)
![image](https://user-images.githubusercontent.com/35115304/227740547-fa471fb4-1c49-406e-bb30-5f8e9c3d1c6a.png)
![image](https://user-images.githubusercontent.com/35115304/227740557-6fea492c-f1ca-49f5-a399-c74f1fbf0699.png)

.

**Comment by Noaaan** [comment]
This blacklist is for biomes, not dimensions. Could you try changing your entries to match them?

**Comment by itsdinkd** [comment]
> This blacklist is for biomes, not dimensions. Could you try changing your entries to match them?

oof. okay. will report back if I still see ore in a newly generated world
