### ISSUE TITLE
[Compat] With Expert weapons and tool

### ISSUE THREAD

**Issue by DanMeadWasTaken** [Noaaan/MythicMetals#151]
[Expert Weapons and tools mod](https://www.curseforge.com/minecraft/mc-mods/expert-weapons) makes progression a little slow by changing recipes in the game. 
Mythic metals appears to have support for the armor, but not the weapons/tools.

**Comment by DanMeadWasTaken** [comment]
After a talk with the simply swords author, it would seem this may be an endeavor that'd be much harder than I originally thought. So, I have decided to possibly integrate this myself in my pack using kubejs. 

I'll leave this open for now though in case anyone wishes to discuss this further.

**Comment by Noaaan** [comment]
I am not the maintainer of this compatibility layer. I believe Xanthian themselves made the tool compat.
I would be happy to provide hooks or ideas on how to implement this should it be needed, but generally I do not wish to have all of this in base Mythic Metals at the moment. 
Generally the sheer quantity of assets and items is the big concern when dealing with compat, which is not something I can definitely provide. I don't consider myself to be very proficient in terms of creating new pixelart 😅
