### ISSUE TITLE
Player keeps getting dropped from server

### ISSUE THREAD

**Issue by Feyrxse** [Noaaan/MythicMetals#152]
Minecraft 1.19.2
Fabric Loader 0.14.14
Fabric API 0.73.2

The player keeps getting dropped from the server, removing the mythic metals mod seems to have fixed the issue. Other players with the same (custom) mod pack are unaffected. The error seems to be "java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 9"

[crash-2023-02-26_22.25.12-client.txt](https://github.com/Noaaan/MythicMetals/files/10890583/crash-2023-02-26_22.25.12-client.txt)
[latest.log](https://github.com/Noaaan/MythicMetals/files/10890584/latest.log)

Here are the player's crash log and latest log files.

**Comment by Noaaan** [comment]
The crash seem related to Reach Entity Attributes somehow. I will look more into it once I have more time.
I do have to ask if this server is hosted via "Open to LAN", as the crash report specifies an integrated singleplayer server.

**Comment by Feyrxse** [comment]
The server is not hosted via open to plan. I used aternos (also sorry for the close/reopen I've never used github :')

Edit: If need be, i can have them try connecting to the server again, and then send me the files just to see if the "integrated singleplayer server" specified in the crash report comes up again.

**Comment by Noaaan** [comment]
I would like that, since this crash is kinda hard to pinpoint

**Comment by Noaaan** [comment]
Are you still experiencing this issue? If so please re-open it. For now I will close it as it is getting kinda stale.
