### ISSUE TITLE
my game crashes after building an Alloy Forge

### ISSUE THREAD

**Issue by krisszip** [Noaaan/MythicMetals#153]
( I use a translator to communicate, I don't speak English )

hi, just after building any alloy forge, and clicking on it, my game freezes, crashes, then closes
(my game is in 1.19.2)

**Comment by Noaaan** [comment]
Are you using Charm? If so this is a duplicate issue of #135. If this is not the case, please upload a crash report

**Comment by Noaaan** [comment]
Do you still have this problem? I will close this issue for now as I assume it was either resolved or it is stale. Please re-open it if you are still experiencing issues.
