### ISSUE TITLE
[1.19.2] crashes when interacting with the forge controller

### ISSUE THREAD

**Issue by Ellisesan** [Noaaan/MythicMetals#157]
I tried the solutions from past issues but that doesn't seem to work, like the charm fixer mod. 

This was the error code I was given:

Time: 2023-03-29 20:50:31
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void io.wispforest.owo.client.screens.ScreenUtils.generatePlayerSlots(int, int, net.minecraft.class_1661, java.util.function.Consumer)'
	at wraith.alloyforgery.AlloyForgeScreenHandler.<init>(AlloyForgeScreenHandler.java:55)
	at wraith.alloyforgery.block.ForgeControllerBlockEntity.createMenu(ForgeControllerBlockEntity.java:309)
	at net.minecraft.class_3222.method_17355(class_3222.java:1040)
	at wraith.alloyforgery.block.ForgeControllerBlock.method_9534(ForgeControllerBlock.java:66)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:964)
	at net.minecraft.class_3225.method_14262(class_3225.java:338)
	at net.minecraft.class_3244.method_12046(class_3244.java:1145)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Noaaan** [comment]
Which version of Alloy Forgery and owo-lib are you using here?

**Comment by Ellisesan** [comment]
I am using Alloy Forgery on 2.0.16 and owo-lib on 0.9.3

**Comment by Noaaan** [comment]
I recommend trying to update to latest Alloy Forgery to 2.0.19 at least, as  I assume you are playing 1.19.2 due to these mod versions.

**Comment by Ellisesan** [comment]
I did but still crashes.

**Comment by Noaaan** [comment]
I am able to launch fine using these versions of both Alloy Forgery and owo-lib. Could you provide a full crash report? I recommend uploading it to a site like https://mclo.gs

**Comment by Ellisesan** [comment]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-03-29 20:59:44
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void io.wispforest.owo.client.screens.ScreenUtils.generatePlayerSlots(int, int, net.minecraft.class_1661, java.util.function.Consumer)'
	at wraith.alloyforgery.AlloyForgeScreenHandler.<init>(AlloyForgeScreenHandler.java:55)
	at wraith.alloyforgery.block.ForgeControllerBlockEntity.createMenu(ForgeControllerBlockEntity.java:309)
	at net.minecraft.class_3222.method_17355(class_3222.java:1040)
	at wraith.alloyforgery.block.ForgeControllerBlock.method_9534(ForgeControllerBlock.java:66)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:964)
	at net.minecraft.class_3225.method_14262(class_3225.java:338)
	at net.minecraft.class_3244.method_12046(class_3244.java:1145)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1669161824 bytes (1591 MiB) / 4580179968 bytes (4368 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f91
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3141
	Graphics card #1 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 128.00
	Graphics card #1 deviceId: 0x15d8
	Graphics card #1 versionInfo: DriverVersion=27.20.22025.2003
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20800.90
	Virtual memory used (MB): 17581.10
	Swap memory total (MB): 12800.00
	Swap memory used (MB): 1315.28
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6144m -Xms256m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19.1-fabric0.58.5-1.3.1
		advancementplaques: Advancement Plaques 1.4.6
		adventurez: AdventureZ 1.4.17
		alloy_forgery: Alloy Forgery 2.0.16+1.19
		ambientsounds: Ambient Sounds (Fabric) 5.2.13
		animatica: Animatica 0.5+1.19
		antighost: AntiGhost 1.19.1-fabric0.58.5-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.5.69
		armorpointspp: Armorpoints++ 3.0.9
			fiber: fiber 0.23.0-2
		balm-fabric: Balm 4.5.7
		basicshields: Basic Shields [Fabric] 1.4.0-pre2-1.19.2
		bclib: BCLib 2.1.6
		bedspreads: Bedspreads 6.0.0+1.19.2
		betteranimationscollection: Better Animations Collection 4.0.5
		bettercombat: Better Combat 1.6.2+1.19
		betterend: Better End 2.1.4
		bettermounthud: Better Mount HUD 1.2.0
		betternether: Better Nether 7.1.3
		betterthanmending: BetterThanMending 1.3.0
		betterthirdperson: Better Third Person 1.8.1
		bettertridents: Better Tridents 4.0.2
		borderlessmining: Borderless Mining 1.1.5+1.19
		bydesign: By Design 1.0.3
		capes: Capes 1.4.5+1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		cem: Custom Entity Models 0.7.1
			completeconfig-base: completeconfig-base 2.0.0-beta.3
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0-beta.3
		charmofundying: Charm of Undying 6.1.1+1.19.2
		chime: Chime 1.3.0
		citresewn: CIT Resewn 1.1.2+1.19.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.2+1.19.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+14
		colormatic: Colormatic 3.1.2+mc.1.19
		combatroll: Combat Roll 1.1.5+1.19
		continuity: Continuity 2.0.1+1.19
		cpm: Customizable Player Models 0.6.6a
		creativecore: CreativeCore (Fabric) 2.9.3
		cull-less-leaves: Cull Less Leaves 1.0.6
			conditional-mixin: conditional mixin 0.3.0
		debugify: Debugify 2.8.0
		distinguishedpotions: Distinguished Potions 4.0.1
		dragonloot: DragonLoot 1.1.2
		dungeons_arise: When Dungeons Arise 2.1.54
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		easyshulkerboxes: Easy Shulker Boxes 4.3.7
		eatinganimationid: Eating Animation 1.9
		elytraslot: Elytra Slot 6.1.0+1.19.2
		enchantinginfuser: Enchanting Infuser 4.2.2
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		entity_texture_features: Entity Texture Features 4.3.0
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		extended_armor_bars: Extended Armor Bars 1.2.1
		fabric-api: Fabric API 0.70.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.21+4d0d570390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.23+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.4+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.14+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.10+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.31+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.39+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.4+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.32+4d0d570390
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.32+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.2+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.24+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.22+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.20+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.9+6e0787e690
			fabric-networking-v0: Fabric Networking (v0) 0.3.26+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.4+4d0d570390
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.30+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.1.1+6e0787e690
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.18+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.23+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.26+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+08b73de490
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.31+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.5+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.23+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.4+4d0d570390
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.0+kotlin.1.8.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.18
		fabricshieldlib: Fabric Shield Lib 1.6.1-1.19
			mm: Manningham Mills 2.3
		fabricskyboxes: FabricSkyBoxes 0.6.1+mc1.19.2
		fabrishot: Fabrishot 1.9.1
		fallingleaves: Falling Leaves 1.13.0+1.19.2
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		farmersknives: Farmer's Knives 2.4
		farsight: Farsight Mod 1.19-2.4
			com_github_jctools_jctools_jctools-core: jctools-core v4.0.1
		ferritecore: FerriteCore 5.0.3
		firstperson: FirstpersonModel 2.2.0
		forgeconfigapiport: Forge Config API Port 4.2.11
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		fsb-interop: FabricSkyBoxes Interop 1.1.3+mc1.19.2-build.25
		ftblibrary: FTB Library 1902.3.13-build.175
		ftbultimine: FTB Ultimine 1902.3.5-build.65
		fwaystones: Fabric Waystones 3.0.7+mc1.19.2
		hidearmor: Hide Armor 2.5
		horseexpert: Horse Expert 4.0.0
		icarus: Icarus 1.13
		iceberg: Iceberg 1.0.46
		illuminations: Illuminations 1.10.11
		indium: Indium 1.0.9+mc1.19.2
		inventoryprofilesnext: Inventory Profiles Next 1.9.1
		invmove: InvMove 0.8.2
		iris: Iris 1.5.0
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		isxander-main-menu-credits: Main Menu Credits 1.1.1
		itemmodelfix: Item Model Fix 1.0.3+1.19
		jamlib: JamLib 0.6.0+1.19
		java: OpenJDK 64-Bit Server VM 17
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		languagereload: Language Reload 1.4.1
		lazydfu: LazyDFU 0.1.3
		leavemybarsalone: Leave My Bars Alone 4.0.0
		legendarytooltips: Legendary Tooltips 1.2.6
		letsleepingdogslie: Let Sleeping Dogs Lie 1.1.1
		levelz: LevelZ 1.4.6
			libgui: LibGui 6.0.1+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		libipn: libIPN 2.0.3
		lithium: Lithium 0.10.4
		memoryleakfix: memory Leak Fix 1.19.3-0.7.0
		midnightcontrols: MidnightControls 1.7.1+1.19
			org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		minecraft: Minecraft 1.19.2
		mixin-conflict-helper: Mixin Conflict Helper 1.2.0
		mixintrace: MixinTrace 1.1.1+1.17
		modmenu: Mod Menu 4.1.2
		morebannerfeatures: More Banner Features 1.1.3
		morechathistory: MoreChatHistory 1.1.1
		moremobvariants: More Mob Variants 1.0.1
		mythicmetals: Mythic Metals 0.17.3+1.19.2
			additionalentityattributes: Additionalentityattributes 1.2.0+1.19
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		myvillage: My Village Pack 1.0.0
		naturescompass: Nature's Compass 1.19.2-2.1.0-fabric
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		nofade: No Fade 1.18-2.0.1
		notenoughanimations: NotEnoughAnimations 1.6.2
		optigui: OptiGUI 1.1.6
			org_apache_commons_commons-text: commons-text 1.9
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
		origins-plus-plus: Origins++ 2.0
		owo: oωo 0.9.3+1.19
			blue_endless_jankson: jankson 1.2.1
		pehkui: Pehkui 3.7.0+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		player-animator: Player Animator 1.0.2
		puzzle: Puzzle 1.4.0-1.19
			puzzle-base: Puzzle Base 1.4.0-1.19
			puzzle-gui: Puzzle GUI 1.4.0-1.19
			puzzle-models: Puzzle Models 1.4.0-1.19
			puzzle-splashscreen: Puzzle Splash Screen 1.4.0-1.19
		puzzleslib: Puzzles Lib 4.3.12
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		rightclickharvest: Right Click Harvest 3.1.0+1.19-1.19.2
		roughlyenoughitems: Roughly Enough Items 9.1.591
			error_notifier: Error Notifier 1.0.9
		shouldersurfing: Shoulder Surfing Reloaded 2.3.0
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothswapping: Smooth Swapping 0.6
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		soulfired: Soul fire'd 3.0.0.0
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.18
		starlight: Starlight 1.1.1+fabric.ae22326
		takesapillage: Takes a Pillage 1.0.4
			midnightlib: MidnightLib 1.0.0
		toomanyorigins: TooManyOrigins 0.7.2+1.19
			apugli: Apugli 1.13.2+1.19
		tradingpost: Trading Post 4.2.0
		trinkets: Trinkets 3.4.2
		universalenchants: Universal Enchants 4.2.15
			extensibleenums: Extensible Enums 4.0.0
		voidtotem: Void Totem 2.1.0
		weaponmaster: YDM's Weapon Master 3.0.2
		wolfarmorcompat: Wolf Armor Compat 1.0.2-1.19.2
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
			maybe-data: Maybe data 1.3.2-1.19-rc2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		xaerominimap: Xaero's Minimap 23.1.0
		yet-another-config-lib: YetAnotherConfigLib 1.7.1
		yosbr: YOSBR 0.1.1
		zoomify: Zoomify 2.9.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.5
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.5
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.5
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.5
	Loaded Shaderpack: ComplementaryReimagined_r2.0.3.zip
		Profile: Custom (+17 options changed by user)
	NEC status: No NEC detected
	Server Running: true
	Player Count: 1 / 8; [class_3222['Xyzc_'/95, l='ServerLevel[New World]', x=1348.01, y=68.00, z=-244.08]]
	Data Packs: vanilla, Fabric Mods, file/Cosmic_KitsuneV1.0.1
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.18-1.19.2

**Comment by Ellisesan** [comment]
https://mclo.gs/6sTLJjz

**Comment by Noaaan** [comment]
According to this log you are using the **old beta** version of Alloy Forgery, which considering its age does not work with latest owo-lib. Again, please update to the latest version for 1.19.2, which is 2.0.19: https://modrinth.com/mod/alloy-forgery/version/2.0.19+1.19

**Comment by Ellisesan** [comment]
I see, ill try it again. Thanks

**Comment by Ellisesan** [comment]
Its working now, I guess I did not install the latest version for some reason. Thank you!

**Comment by FlamingTM** [comment]
Same thing, using latest version of owo lib, mythic metals, and allow forgery on 1.19.2
Crash Logs: [https://mclo.gs/ED6Ogff](url)

**Comment by Noaaan** [comment]
Then open a new issue. Either way, this is related to [Alloy Forgery](https://github.com/wisp-forest/alloy-forgery), not Mythic Metals. This crash is also a duplicate of https://github.com/wisp-forest/alloy-forgery/issues/80
