### ISSUE TITLE
[Suggestion] New minerals (ChatGPT auto-suggestion)

### ISSUE THREAD

**Issue by ghost** [Noaaan/MythicMetals#162]
When it comes to adding new resources to the Mythic Metals mod, there are a variety of different options. Here are a few ideas that could be interesting to players:
 1. Aetherium: A rare, magical metal that's infused with the power of the Aether. It could be used to create powerful weapons, armor, and tools that give the player special abilities, such as increased speed or the ability to fly.
 2. Crystalith: A type of crystal that's found deep underground. It could be used to create powerful weapons and armor that have special enchantments, such as increased durability or the ability to reflect magic.
 3. Meteorite: A type of metal that's only found in meteorites that crash to Earth. It
 could be used to create powerful weapons and armor that have high damage and durability, making them great for taking on tough enemies. 
4. Shadowsteel: A dark, mysterious metal that's imbued with the power of the void. It could be used to create weapons and armor that have powerful lifesteal abilities, allowing the player to regain health as they fight. 

These are just a few examples of the types of resources that could be added to the Mythic Metals mod to enhance its gameplay. Ultimately, the possibilities are endless, and it's up to the development team to decide which resources would be most interesting to players.

(This suggestion was created half-automatically, if it's a bad quality suggestion then close the issue)

**Comment by Noaaan** [comment]
If I want to use ChatGPT to brainstorm/generate new ideas I would probably be using it already. The material names are kinda interesting, although I do not see myself adding any new metals right now, and *especially* not new ores. 

Also, Aetherium *used* to be a material in Mythic Metals, but was removed to reduce the scope of the mod.

**Comment by Mahadbaloch** [comment]
Reduce the scope of the mod?
