### ISSUE TITLE
Recipes!

### ISSUE THREAD

**Issue by 0wdg** [Noaaan/MythicMetals#167]
When I try to craft either Metallurgium or Celestium armor it just doesn't craft. Please help on the reason why or fix the issue. Or either propose a thing I am not doing right. Please help me. 

![celestium chesplate failed crafting](https://github.com/Noaaan/MythicMetals/assets/133618445/85d9a229-bc43-4efc-8ace-10bb97a396fa)
![metallurgium chestplate failed crafting](https://github.com/Noaaan/MythicMetals/assets/133618445/10ed4175-01ec-49ac-988b-2a810e49ed8a)

**Comment by Noaaan** [comment]
Both of these items use the smithing table, in fact, they should show up in REI.
Metallurgium armor upgrades Netherite gear, and Celestium upgrades Diamond gear.

**Comment by 0wdg** [comment]
Thanks very much!
