### ISSUE TITLE
How do i craft a carmot staff

### ISSUE THREAD

**Issue by basconboiboss** [Noaaan/MythicMetals#174]
I cant find a way to craft it

**Comment by Noaaan** [comment]
You craft the staff using a Kyber Shovel and a Block of Carmot in a Smithing Table. This might be referenced in the advancements. This documentation has been improved as in 1.20 it uses a Smithing Template instead. 

In the future, please ask gameplay questions either in the CurseForge comment section, or in the Wraith Discord server linked on the mod page. Especially in the Discord you can expect to be answered much quicker.
