### ISSUE TITLE
Crash starting server 1.20

### ISSUE THREAD

**Issue by hoekzemaar** [Noaaan/MythicMetals#175]
Game loads fine but starting server just adding Mythic Metals gives a crash. Any idea?
[latest.log](https://github.com/Noaaan/MythicMetals/files/11711469/latest.log)

**Comment by Noaaan** [comment]
This log seems incomplete, there is nothing here pointing to a crash. Do you have a crash report?

**Comment by Noaaan** [comment]
Someone in Discord has confirmed this crash, and I think I have found a fix for it.

**Comment by hoekzemaar** [comment]
> This log seems incomplete, there is nothing here pointing to a crash. Do you have a crash report?

This is all i have unfortunately. No crash log
