### ISSUE TITLE
mythicmetals-0.18.1+1.20-hotfix crash without Alloy Forgery mod installed

### ISSUE THREAD

**Issue by lospejos** [Noaaan/MythicMetals#176]
On Minecraft `1.20`, Fabric `fabric-api-0.83.0+1.20`, Mythic Metals `mythicmetals-0.18.1+1.20-hotfix`, when Alloy Forgery mod is not installed, crash on startup, complaining absent `Alloy Forgery`.

On previous mod version `mythicmetals-0.18.0+1.20` this error was not appeared.

**Comment by Noaaan** [comment]
Yes, this is intentional. The mod is fundamentally not playable without it, and this was an oversight which was corrected in this fix.
