### ISSUE TITLE
Game crash upon starting world 1.19.4

### ISSUE THREAD

**Issue by Cyberdragon577** [Noaaan/MythicMetals#177]
when I start a world on MC version 19.4 whether it be new or existing it crashes before it can load and says shaders null

[crash-2023-06-17_03.04.41-client.txt](https://github.com/Noaaan/MythicMetals/files/11778325/crash-2023-06-17_03.04.41-client.txt)

**Comment by Noaaan** [comment]
You are using OptiFine, which is not supported. It causes many incompatabilities, which are impossible to fix. Try disabling it and see if you still crash

**Comment by Cyberdragon577** [comment]
yeah that worked thank you
