### ISSUE TITLE
Tools not showing up in Just Enough Items

### ISSUE THREAD

**Issue by ShrimpedKeyboard** [Noaaan/MythicMetals#178]
For some reason tools, Blocks (- Forge controllers) and Armors are not showing up in JEI even with JER is there any way to fix this or is this intentional ive spent basically 2 days trying to make a mythril Drill and a stormyx sheild 
![image_2023-06-26_165020489](https://github.com/Noaaan/MythicMetals/assets/59605048/8b897df9-4c19-4a09-95e8-4d9a7fab39b0)

**Comment by Noaaan** [comment]
There is generally way to little information to go on here, and I would like it if you could provide more details regarding this issue.
Especially your full modlist, which you can find in your `latest.log` inside your instances logs folder. Go here for more details: https://fabricmc.net/wiki/player:tutorials:logs_ml:windows

Generally JEI has not been supported on Fabric for a long period of its history, and as such alternatives like Roughly Enough Items or EMI are better. After submitting your logs I would advice you to try these out instead, and see if the rest of the Kyber blocks/ores/tools reappear.

**Comment by Noaaan** [comment]
Bumping this issue, are you still experiencing this problem?

**Comment by ShrimpedKeyboard** [comment]
Still experiencing but we just switch to emi works perfectly on there sorry i swear i replied but i must of forgot

**Comment by Noaaan** [comment]
This should be fixed with later versions of JEI, as seen in the linked issue.
