### ISSUE TITLE
Compatibility - MMv1.18.0/1.18.1 & RER 2.8.0

### ISSUE THREAD

**Issue by rxay579** [Noaaan/MythicMetals#179]
I think there may be an incompatibility introduced in Mythic Metals v1.18.0 for MC 1.19.4 with Roughly Enough Resources v2.8.0.
When logging into a single player world, the loading gets to 100%, then goes to "Connection Lost" "Invalid player data".
Screen snippet attached.
![Single-Player](https://github.com/Noaaan/MythicMetals/assets/67221030/08b16ae8-c5aa-4db5-ac60-23fe194db3f3)

I'm not seeing the issue with Mythic Metals v1.17.6 on the same mod setup.
Have only been testing in a single player world so far.
Logs attached for the same instance launching and logging in with MM v1.17.6, v1.18.0, v1.18.1, and v1.18.1 with RER disabled.
MC name and UUID edited.
[mm-1.17.6.txt](https://github.com/Noaaan/MythicMetals/files/11878733/mm-1.17.6.txt)
[mm-1.18.0.txt](https://github.com/Noaaan/MythicMetals/files/11878735/mm-1.18.0.txt)
[mm-1.18.1.txt](https://github.com/Noaaan/MythicMetals/files/11878738/mm-1.18.1.txt)
[mm-1.18.1 - no RER.txt](https://github.com/Noaaan/MythicMetals/files/11878739/mm-1.18.1.-.no.RER.txt)

**Comment by Noaaan** [comment]
I believe this issue was identified in https://github.com/fzzyhmstrs/EMI_loot/issues/26, and has already been fixed as of https://github.com/Noaaan/MythicMetals/commit/23e0f748518a697871fa1e1e4a5ac1e9ea81319b.
It is scheduled for next release

**Comment by rxay579** [comment]
Thanks, I'll re-test next update.

**Comment by rxay579** [comment]
Was able to test with MC v1.20.1, MM v1.8.2, MM Deco v0.5.5, REI v12.0.634, and all their requirements in single player.
The world appeared to create and load as normal.
No extended testing yet.

Any chance MM v1.8.2 can still compile for MC v1.19.4 so the MM 1.8.x improvements can be used there?
Understandable if you've moved on to MC v1.20.x.

**Comment by Noaaan** [comment]
I am planning on backporting the bugfixes to 1.19.4 sometime, just haven't gotten around to it yet.
