### ISSUE TITLE
Issue with recipes via Alloy Smelter

### ISSUE THREAD

**Issue by Oscienet** [Noaaan/MythicMetals#18]
Looks like there is another issue with tags, because via Alloy Smelter argonium's recipe (Midas Gold+Midas Gold) isn't the same as via Smithing Table (Gold+Midas Gold)
Similar issue with celestium, via smelter it's recipe is Quadrillium+Starrite and via table its Kyber+Starrite 
Here are screenshots from REI, as an example, again
![image](https://user-images.githubusercontent.com/74426790/103441403-be672680-4c5e-11eb-989a-2fcccdb94b98.png) ![image](https://user-images.githubusercontent.com/74426790/103441406-ce7f0600-4c5e-11eb-8ed2-4118e6f4c726.png)
(I think you are already aware of this, but just in case, I've still reported it)

**Comment by Noaaan** [comment]
Was aware of the Argonium issue. Midas Gold can be used as gold, hence the double recipe shenanigans. I was not aware of the other issue however. Thanks for putting it up.

**Comment by Noaaan** [comment]
Should be fixed in latest commits
