### ISSUE TITLE
Trinkets Compatibility with Celestium Elytra

### ISSUE THREAD

**Issue by muon-rw** [Noaaan/MythicMetals#181]
Hi metalsguy, it'd be so poggers if you

1. Add celestium elytra to `data/trinkets/tags/items/chest/cape.json` so it can be equipped in the trinkets cape slot, 

2. Make it render and have the attribute modifiers apply while in a trinkets slot. I am not smart enough for this otherwise this would have just been a PR.

**Comment by Noaaan** [comment]
1: I think this should be feasible. Might make this only apply if mods like Elytra Slot is installed, as I believe it is more appropriate
2: Not sure about this one, since it would potentially make the mod dependent on Trinkets API, which is not within scope for this project. Depending on how it works, it would probably be put in an addon or something later.

**Comment by muon-rw** [comment]
Oops, I didn’t even know Elytra slot was a separate mod. I thought Trinkets added the elytra there itself. I agree in that case. 

On 2, BetterEnd has an implementation (with the Armored and Crystalite Elytra) probably quite similar to what you would want to go for, and has Trinkets as an optional dependency.

**Comment by Noaaan** [comment]
What I mean by dependency in this context is in terms of code: which their implementation does use, and isn't something I wish to maintain in this project. 

In the future I might make some addon/other project that probably could easily do this/something similar, but specifically regarding attributes - the point of the Celestium Elytra is that you *don't* need the attributes while in a separate slot, as it is an **armored** Elytra. 

For now I will do some testing with it and see how it works.

**Comment by Noaaan** [comment]
This has been implemented on Elytra Slots side as of https://github.com/illusivesoulworks/elytraslot/issues/79#event-13128587209
I will revisit this once I get a new model for the Elytra
