### ISSUE TITLE
Bug: Mythic Metals Messes Up The "Sodium Extra" and "Reese's Sodium Options" Video Settings Menu

### ISSUE THREAD

**Issue by NoobWithAUniqueName** [Noaaan/MythicMetals#184]
I was playing one day and decided to change my render distance, when I opened video settings this was what I found:

![image](https://github.com/Noaaan/MythicMetals/assets/138097838/518082d8-8b05-46ef-8639-c3f659be8c1b)

What it's supposed to look like:

![image](https://github.com/Noaaan/MythicMetals/assets/138097838/4100da7c-58ea-4655-810d-4085170e29d1)

Usually I wouldn't post anything for a minor annoyance like this, but Sodium Extra and Reese's Sodium Options are used by quite a decent amount of people as told from Curseforge and Modrinth's download numbers.

"How do you know it's Mythic Metals causing the problem?"
I know because I ran Minecraft (on Fabric) with:

-Fabric API
-Sodium
-Sodium Extra
-Reese's Sodium
-Alloy Forgery
-Owolib
-Mythic Metals

With that minimalistic mod combination, the bug still appeared. When I took Mythic Metals out, the bug vanished. This means that it's definitely Mythic Metals itself causing the bug and not its dependencies.

"Does the bug still occur without Reese's Sodium Options?"
Yes. Below is the image of what it's supposed to look like:

![image](https://github.com/Noaaan/MythicMetals/assets/138097838/79a492a3-678b-4a19-8813-e779b1b37bc7)

What it looks like when using Mythic Metals is used:

![image](https://github.com/Noaaan/MythicMetals/assets/138097838/ad50fb8f-1058-42f2-bfae-301aa5ed7f28)

All in all, this is most likely low priority compared to the other stuff you need to do, but I just wanted to point it out there since it doesn't seem like anybody else is gonna.

I tried to make it as detailed and straightforward as possible, but if you need me to test anything else lmk. Now if you'll pardon me, I need to fold my Royal Midas Sword for the 3886th time.

**Comment by Noaaan** [comment]
I believe this issue is related to owo-lib: https://github.com/wisp-forest/owo-lib/issues/142
A future release should contain the fix for this.

**Comment by NoobWithAUniqueName** [comment]
I see, then I guess I'll be awaiting that release then.

**Comment by Noaaan** [comment]
Should be fixed on Sodiums end
