### ISSUE TITLE
unable to start with pehkui

### ISSUE THREAD

**Issue by gitguette** [Noaaan/MythicMetals#185]
minecraft is unable to start on 1.19.2 with pehkui also installed. the game opens a window, but draws nothing in it and closes shortly after. full error log [here](https://pastebin.com/J1vbixCH)

**Comment by Noaaan** [comment]
The log provided is unavailable. Could you post it again?

**Comment by gitguette** [comment]
[does this one work?](https://pastebin.com/x7kpf5Ya)

**Comment by gitguette** [comment]
[sure](https://gist.github.com/gitguette/6fe022edc15a1142ba831acc3e0a0442)

**Comment by Noaaan** [comment]
I do not see any mention of Mythic Metals or its dependencies in this crash. Are you sure this is the cause of your issue? The stack trace mentions MemoryLeakFix, it might be some incompatibility with that and Pehkui.

**Comment by gitguette** [comment]
memory leak didn't fix it, but crashes don't happen if no other mods but pehkui, mythic metals, and dependencies are enabled, which is weird since it only started happening after installing mythic metals

**Comment by Noaaan** [comment]
Strange... I will take a look at it. Thanks for reporting.
*Note that the 1.19.2 builds are starting to get old, and won't be recieving new features, and are strictly low priority/not supported*

**Comment by Noaaan** [comment]
Using the following versions do not reproduce the issue:

- `fabric-api-0.76.1+1.19.2`
- `mythicmetals-0.17.3+1.19.2`
- `owo-lib-0.9.3+1.19`
- `Pehkui-3.7.8+1.14.4-1.20.1`
- `wraith-alloy-forgery-2.0.20+1.19`

Do you still experience this issue? Looking deeper at the logs makes this seem like some crash with some older compat Mixin via Pehkui. This might have been removed/changed in later versions of Pehkui. If this is not the case then I might know what the incompat is, as Mythic Metals does have some methods to change mining speeds, specifically when using an Orichalcum Hammer or Mythril Drill.
