### ISSUE TITLE
Stormyx Shield new Feature?

### ISSUE THREAD

**Issue by DiamondkingID** [Noaaan/MythicMetals#195]
potentially see if you can add banner support to the stormyx shield?
-such as rounding the banner pattern to fit
-more work but add a rounded banner that uses same or similar banner patters
-or something better
sorry if i did this wrong, if i did it wrong just delete.

**Comment by Noaaan** [comment]
Adding banner patterns to the Stormyx Shield is currently not planned. Mainly this is due to having to re-do all existing banner patterns to fit it. If I were to add such a feature I would also want to make it compatible with banner patterns from other mods, which currently isn't feasible.
