### ISSUE TITLE
Changes Z Position for text elements not a part of the mod

### ISSUE THREAD

**Issue by VoidedMirror** [Noaaan/MythicMetals#200]
This mod moves many text elements in containers and inventories by 5 points towards the camera. This messes with mods/resourcepacks that depend on the default vanilla text display behaviors. 

I'm not sure why this was done to the Vanilla text system, but it should be possible to resolve any issues this had by only affecting Mythic Metals text system.

**Comment by Noaaan** [comment]
There should not be any code in this mod which changes this behavior. Could you provide more details on reproducing this issue? If you could attach your `latest.log`, which contains many useful details (like a full modlist with versions, and your Minecraft version) it would be a great help. As well as the name of the resource packs you have experienced this issue with

**Comment by VoidedMirror** [comment]
I did some more testing. Seems it's not Mythic Metals doing it but the behavior changed when I disabled only Mystic Metals from the pack I'm testing with. Sorry for the confusion seems some other mod is responsible.

**Comment by VoidedMirror** [comment]
Yeah it seems to be an issue with mods that use owo-lib. I'll post the issue over on their page.

**Comment by Noaaan** [comment]
Main reason I am asking about versions is that a similar issue was fixed in [0.11.2](https://github.com/wisp-forest/owo-lib/releases/tag/0.11.2%2B1.20)

**Comment by VoidedMirror** [comment]
Yeah looks like that is the exact issue and I was using the 0.11.1 version of owo-lib, Looks like this issue was resolved by updating to 0.11.2. Thanks for your help btw
