### ISSUE TITLE
Some Reworked Textures.

### ISSUE THREAD

**Issue by sasadness** [Noaaan/MythicMetals#201]
I really like the mythic metals mod but whem im playing i feel like some textures could be better, so i reworked some of them.
I tested all the textures i reworked and i think they look really nice in game.
Feel free to use if u want.

![image](https://github.com/Noaaan/MythicMetals/assets/143923541/0b23515e-f033-44a0-85b9-ce5ebef138a3)
![Mythic_Texture_Comp](https://github.com/Noaaan/MythicMetals/assets/143923541/9a2a65a4-ce1c-4dd2-9719-f697a51b5e9d)

![durasteel_sword](https://github.com/Noaaan/MythicMetals/assets/143923541/42ff1284-76da-45c6-9745-4bd7bc5f6200)
![hallowed_sword](https://github.com/Noaaan/MythicMetals/assets/143923541/3a4282ab-3ebf-4f49-b47b-6d0b45cd3af8)
![metallurgium_axe](https://github.com/Noaaan/MythicMetals/assets/143923541/ebc65612-8564-4ab1-aa35-2b8e20099617)
![metallurgium_hoe](https://github.com/Noaaan/MythicMetals/assets/143923541/3a16a4f7-67d8-40e2-b631-56b052c4eb14)
![metallurgium_shovel](https://github.com/Noaaan/MythicMetals/assets/143923541/ad1c148c-208b-48d0-a6a6-0cfc10ad6a41)
![metallurgium_sword](https://github.com/Noaaan/MythicMetals/assets/143923541/8febd9fc-739e-48ea-bf7f-55fa8ddc466e)
![orichalcum_sword](https://github.com/Noaaan/MythicMetals/assets/143923541/74a9c8cd-3783-4501-b291-2e626b860e71)

**Comment by Azzyypaaras** [comment]
![Untitled_Artwork(59)](https://github.com/Noaaan/MythicMetals/assets/20349662/0215016c-5607-4d5b-96b9-2ea542d168fb)
awawawawa

**Comment by Noaaan** [comment]
Please don't post unrelated concept art. 
I will get back to comment on this PR properly, once I find the time

**Comment by Noaaan** [comment]
Sorry for the wait. I have taken some time to think about your textures and I wanted to make these points:
- The Metallurgium Sword is a nice sword, although it is relatively simple for what I want with the set at the moment.
- The Orichalcum Sword looks weird, I do not like it. The strip is too chaotic, and the guard is too dark.
- The Durasteel Sword is ok, albeit the lighting is a bit flat. To be more consistent with other sprites it should be darker there
- The Hallowed Sword is ok. With the original texture being a reference to Terrarias [Excalibur](https://terraria.fandom.com/wiki/Excalibur), your rework is takes away its identity in this regard. I do agree the larger white area is more consistent with the rest of the set though. 

Overall I think I see the theme you are going for (take this with a grain of salt, as I could definitely be wrong), which is slightly more vanilla-themed and more realistic sword textures (straighter blades and guards). I also really appreciate the spirit of trying to improve the textures yourself, thats awesome.

I will not be accepting these textures, as I am currently deep in organizing and working on an ongoing texture rework, and adding these would cause conflict in that regard. Perhaps you could make your own resource pack and publish it to see what other players think?

I wish you luck in your future ventures. Getting into spriting is a long, time consuming, but fruitful journey. 

Cheers
