### ISSUE TITLE
Crashing on opening

### ISSUE THREAD

**Issue by KashiiGang** [Noaaan/MythicMetals#215]
Using fabric 1.18.2 and tried a couple versions of Mythic Metals but they all crash my game upon starting.
[crash-2023-12-04_23.06.27-client.txt](https://github.com/Noaaan/MythicMetals/files/13555023/crash-2023-12-04_23.06.27-client.txt)

**Comment by Noaaan** [comment]
This happens due to you using an outdated version of owo-lib. You need the following version (0.7.2-no-cme): https://www.curseforge.com/minecraft/mc-mods/owo-lib/files/3824297

**Comment by SaptarshiBagchi-05** [comment]
I am facing the same issue on version 1.20.1 and its still doesn't run properly with the latest versions of the 1.20.1 release

**Comment by Noaaan** [comment]
In that case please open a new issue with a new crash log, as these two are unrelated issues

**Comment by Noaaan** [comment]
Are you still experiencing this issue? This has not seen some activity in some time, so I will assume it is resolved. If this is not the case, do feel free to re-open it.
