### ISSUE TITLE
[Compat] w/ Easy Anvils, persistent inventory and visible items.

### ISSUE THREAD

**Issue by dmsw0303** [Noaaan/MythicMetals#218]
Feel like this would probably be pretty simple to add on your end. Did look around for some documentation but couldnt find anything that woudnt require me looking into the files. Assuming its just a tag.

**Comment by Noaaan** [comment]
Currently this is not straight forward to implement with Easy Anvils, as mentioned in this issue: https://github.com/Fuzss/easyanvils/issues/43

Once Fuzss adds a way to opt-in for modded anvils then I would probably add it to the config

**Comment by dmsw0303** [comment]
should have known you already considered this. appreciate the response!

**Comment by Noaaan** [comment]
As of Easy Anvils v20.4.0 for Minecraft 1.20.4 and beyond, MM anvils are now supported.
