### ISSUE TITLE
[Bug Report/Crash] 0.19.0 Fabric Crash on Startup

### ISSUE THREAD

**Issue by dmsw0303** [Noaaan/MythicMetals#220]
Not sure if this is entirely Mythic Metal's fault, my smp modpack is 235 mods deep on the client side. Game was starting before the most recent update, Now the game loads to a blackscreen then immedietly crashes. Usually i can at least understand the log enough to trouble shoot this on my own. But Mythic Metals isnt really listed anywhere here and my log is FILLED with warnings.

https://mclo.gs/q4IXydz // crashlog w Mythic Metals

https://mclo.gs/zVMiGck // w.o Mythic Metals

really sorry if im wasting your time having you look at something thats not your fault. ive just been waiting for the full release of this update and really want some insight into resolving this. appreciate your time and your work!

**Comment by Noaaan** [comment]
Mythic Metals isn't causing these warnings fortunately. I have however identified the launch issue, and I am working on a fix for it.

**Comment by dmsw0303** [comment]
thank you really appreciate it

**Comment by Noaaan** [comment]
Should be fixed as of 0.19.1, which just released
