### ISSUE TITLE
Mythic Metals 0.19.1 broke pickaxes on my server

### ISSUE THREAD

**Issue by Aesthir** [Noaaan/MythicMetals#221]
Since I updated to the newest version this morning, nobody on my server has been able to use a pickaxe. After scanning the logs, I discovered a few lines related to this:

`[Worker-Main-1/ERROR]: Couldn't load tag mythicmetals:conduit_blocks as it is missing following references: mythicmetals:aquarium_glass (from fabric)`
`[Worker-Main-1/ERROR]: Couldn't load tag minecraft:mineable/pickaxe as it is missing following references: #mythicmetals:conduit_blocks (from fabric)`

…and also, after a player who made tidesinger armour logged in:

`[Server thread/ERROR]: Tried to load unrecognized recipe: mythicmetals:armor/tidesinger_leggings removed now.`
`[Server thread/ERROR]: Tried to load unrecognized recipe: mythicmetals:armor/tidesinger_helmet removed now.`
`[Server thread/ERROR]: Tried to load unrecognized recipe: mythicmetals:armor/tidesinger_chestplate removed now.`
`[Server thread/ERROR]: Tried to load unrecognized recipe: mythicmetals:armor/tidesinger_boots removed now.`
`[Server thread/ERROR]: Tried to load unrecognized recipe: mythicmetals:armor/tidesinger_leggings removed now`.
`[Server thread/ERROR]: Tried to load unrecognized recipe: mythicmetals:armor/tidesinger_helmet removed now.`
`[Server thread/ERROR]: Tried to load unrecognized recipe: mythicmetals:armor/tidesinger_boots removed now.`
`[Server thread/ERROR]: Tried to load unrecognized recipe: mythicmetals:armor/tidesinger_chestplate removed now.`

If you need more information, I'd be happy to provide it.

**Comment by SpiritOTHawk** [comment]
confirm

**Comment by Dragon-Seeker** [comment]
I believe that @Noaaan knows of the issues and a fix will come soon. As a stop-gap you can use https://modrinth.com/mod/lmft to prevent the entire tag from being thrown out as to temporary fix issues with mining

**Comment by Noaaan** [comment]
I am aware of this yes. Minecrafts wonderful tag system, which drives gameplay, has no failsafes for cases like this unfortunately. LMFT is a great tool to use in the meantime, as it loads the tag despite a missing entry. 
My plan is to release another fix this evening/tonight if I find the time

**Comment by Noaaan** [comment]
The tag issue is fixed as of latest release: https://github.com/Noaaan/MythicMetals/releases/tag/0.19.2%2B1.20.1

The recipe logspam is something I haven't had the chance to reproduce yet. I would appreciate if you could open that into its own issue should it prove a major issue. If not its fine, although I have noted it down and will look into it when I get the chance.

For now I will close this issue to mark that the major pickaxe breakage has been patched.
