### ISSUE TITLE
Inconsistent naming with blocks

### ISSUE THREAD

**Issue by TrueDevron** [Noaaan/MythicMetals#224]
Although a small issue, I've noticed that the blocks from this mod have different naming when compared to the vanilla version. For example:

"Block of Raw Iron" and "Block of Iron" is the naming convention in vanilla..

Whereas in Mythic Metals it follows as "Raw Banglum Block" and  "Banglum Block"

**Comment by KonSola5** [comment]
See this commit: df0a01d

**Comment by Noaaan** [comment]
This is indeed resolved for the next upcoming patch of Mythic Metals.

**Comment by Noaaan** [comment]
Fixed in 0.19.3
