### ISSUE TITLE
Crash on startup (Fabric 1.20.4) apparently caused by incorrectly targeted method

### ISSUE THREAD

**Issue by Gamemassa** [Noaaan/MythicMetals#226]
MC 1.20.4
Fabric 0.15.7
Mythic Metals 0.19.3

I added Mythic Metals to my custom modpackon Fabric 1.20.4 and it appears to be targeting the wrong getCausingEntity method, resulting in a crash on startup. Crash Report and Latest.Log are linked below.

Crash Report
https://gist.github.com/Gamemassa/630bd7ee3736b1f0aee063a2d59a2e18

Latest.Log
https://gist.github.com/Gamemassa/32aa71f1f0037feb6a9c38598026ec3b

**Comment by Noaaan** [comment]
This issue should be fixed. Could you test this real quick once the GitHub Action completes the build of the jar? I wasn't able to reproduce this in my small test environment (this might only happen with multiple mods targeting explosions installed)

https://github.com/Noaaan/MythicMetals/actions/runs/8165431516/job/22322561469

**Comment by Noaaan** [comment]
Tested and confirmed fixed as of 0.19.4

**Comment by Gamemassa** [comment]
> Tested and confirmed fixed as of 0.19.4

I can also confirm, it's definitely working. Also, just curious, are you planning to update your other mod, Mythic Metals Decorations, for 1.20.4?

**Comment by Noaaan** [comment]
Yes. Main delays have been time-related with testing it properly. Recently I have verified a ton of crashes with it are gone as of that patch, so next step is porting it before working on snapshot stuff

**Comment by Gamemassa** [comment]
> Yes. Main delays have been time-related with testing it properly. Recently I have verified a ton of crashes with it are gone as of that patch, so next step is porting it before working on snapshot stuff

Awesome! Well, no rush; take your time. I know how frustrating modding can be sometimes. And keep up the great work!
