### ISSUE TITLE
items with anonymous names

### ISSUE THREAD

**Issue by Rogenar** [Noaaan/MythicMetals#227]
![ss5](https://github.com/Noaaan/MythicMetals/assets/122460325/a0b841e6-3ac2-4c19-af1d-5301512204aa)
[latest.log](https://github.com/Noaaan/MythicMetals/files/14512233/latest.log)
and also, when I looked at the statistics of the item with the tool status mode, the property ranking changed. for example, the attack speed statistic comes first.

**Comment by Noaaan** [comment]
Seems like I missed Smithing Templates getting new item names for 1.20.4. Previously they all defaulted to use the same name as every other smithing template. Will get this fixed soon

**Comment by Noaaan** [comment]
Did you accidentally close this issue? It isn't resolved yet

**Comment by Rogenar** [comment]
Yes, I closed it by mistake.
