### ISSUE TITLE
No yield from netherite pickaxe

### ISSUE THREAD

**Issue by FewerFlaws** [Noaaan/MythicMetals#23]
It looked like this is true of every ore, but I certainly tested carmot, copper, mythril, and zinc ores.  None of them drop an ore block when mined using a netherite pickaxe.  Diamond works, Gold doesn't, Iron does, Stone doesn't.

Netherite should definitely work if diamond does =]

**Comment by FewerFlaws** [comment]
NOPE, this was an issue on my end.  Sorry about that.

**Comment by Noaaan** [comment]
Did you have a mod that overrode Mining Levels? 😳

**Comment by FewerFlaws** [comment]
Nope, I was hard replacing the list of pickaxes and forgot netherite exists
=P
