### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by CassieRoseZA** [Noaaan/MythicMetals#232]
I downloaded the latest 1.20.4 build from modrinth and now my antivirus is saying its malware

**Comment by CassieRoseZA** [comment]
![image](https://github.com/Noaaan/MythicMetals/assets/13422754/5d2d59a5-6b0b-4551-828a-3c6440af533b)
![image](https://github.com/Noaaan/MythicMetals/assets/13422754/c4eb21b7-42cf-49c9-8789-0b7f2fbe1f26)

**Comment by Noaaan** [comment]
Could you upload your jar to VirusTotal and post the result here?

**Comment by CassieRoseZA** [comment]
https://www.virustotal.com/gui/file/cafe155e902f6e2e13678624bab726cc88625d9fe603ecb9b2f9dfaefce0819e

**Comment by Noaaan** [comment]
The hashes of the jars all match up with my local build, which hopefully should not contain anything malicious. I think this might be a false-positive, although it is definitely better to be on the safe side. I am digging through the jar downloaded from Modrinth and checking whether there is something bad with it

**Comment by Noaaan** [comment]
This is the same jar that is available from CurseForge and GitHub. 
Putting all of the jar-in-jar dependencies through the same scrutiny it comes out without any hits. I scanned them on my Windows laptop too using Windows Defender without any issue. It is very likely that this is a false positive. 
I could not find any malicious code either digging through the compiled jar. I have not dug through the jij, although it is unlikely anything there is causing any issue

https://www.virustotal.com/gui/file/a19a46a248faae2bd2de413f15d522bd43ea7328efe0e719f9a0fa3b2b01778b
https://www.virustotal.com/gui/file/06ef4cd4120b1bad1ba4817476a5403368e4e99e0cfc592cfb17c816ea937cbd
https://www.virustotal.com/gui/file/f9f8a528e7a27216d9949d00ae39a36eb920b0400b1da90745d242cf158bcc9a
https://www.virustotal.com/gui/file/42d2f766f93072b8b218d675d21bcc34562f47c45ad6fc8582716891a8c29ee1
https://www.virustotal.com/gui/file/3e2b921664d91ef819d332d2a6af17bd0d6dbf71fd7d8fe86643ca38cea02fcb
https://www.virustotal.com/gui/file/cafe155e902f6e2e13678624bab726cc88625d9fe603ecb9b2f9dfaefce0819e

**Comment by CassieRoseZA** [comment]
Ok thanks i thought it mighta been a false postive
