### ISSUE TITLE
Is it possible to remove upgrades from the drill?

### ISSUE THREAD

**Issue by Ccasend83** [Noaaan/MythicMetals#233]
I put two separate drill upgrades on the mythril drill but now I want to change one of them. I have tried just right clicking it normally but it doesn't work. I'm just wondering whether if they is an actual way to remove those unwanted upgrades or do I just have to make a new one?

**Comment by Noaaan** [comment]
Mythril Drill upgrades are not removable. If you want to make a new configuration you have to craft a new drill

**Comment by Ccasend83** [comment]
Ok thank you I was just wondering
