### ISSUE TITLE
Unobtanium doesn't spawn

### ISSUE THREAD

**Issue by kimsis** [Noaaan/MythicMetals#234]
I am playing a modpack called Fantasy MC Fabric on 1.20.1.
It uses MyhicMetals 0.19.3.
Currently there is no unobtanium spawned in my world.
I was mining for a few hours, then I gave up.
I changed the texture (so that its more visible) with a small resource pack, put an Xray, got in spectator mod, and started looking. There is 0 unobtanium spawned anywhere between 5 and -54.
I checked the config and it has "unobtanium": true, .... "unobtaniumTemplateChance": 0.25

I haven't been able to find any mention of the mod within the pack, so I could assume the pack hasn't disabled the spawning of this ore, especially when there is even a custom quest for it.
Is there something I am missing? Do I need to do first for unobtanium to start spawning?

**Comment by kimsis** [comment]
Nevermind, I had messed up something in my setup.
I managed to find unobtanium, but it was just so little.... There was one block every 4th chunk or so, I guess this is what is done with the "unobtaniumTemplateChance":0.25

**Comment by Noaaan** [comment]
The Unobtainium Smithing Template Chance does not affect the spawn rate of Unobtainium in any way. It affects how often that item shows up in Ancient City chests. To configure the worldgen you need a datapack
