### ISSUE TITLE
Feedback on Translation Faults in Mythic Metals Mod for Minecraft Version 1.20.1 following the Triggering of April Fool's Day Egg

### ISSUE THREAD

**Issue by c1390818629** [Noaaan/MythicMetals#236]
Dear Mythic Metals Development Team,

I am currently using Minecraft version 1.20.1, along with your Mythic Metals mod (version 0.19.6+1.20.1). Following the activation of the April Fool's Day egg, I encountered some translation faults that have affected my gaming experience, despite the amusing nature of the egg.

The issue: After triggering the April Fool's Day egg, I noticed incorrect translations in certain parts of the mod. For instance, the drop item for Adamantine Ore does not correctly display its Chinese translation, instead showing its English name. Such translation errors are present in various parts of the mod.

I have attempted to reinstall the mod and review the configuration files, but the issue persists.

To assist you in better understanding the issue, I am providing the following detailed information:

Mod Version: 0.19.6+1.20.1
Minecraft Version: 1.20.1
Specific Example of Faulty Translation Text: The drop item for Adamantine Ore displays the English name instead of the Chinese translation.

While acknowledging the translation faults, I would like to commend your team for the creativity and amusement factor of the April Fool's Day egg. The addition of such an egg has indeed added a lot of fun to the game.

Thank you for your diligent efforts and continuous updates to the mod. I look forward to your response and a solution to this issue.

Due to my limited proficiency in English, I utilized AI to assist me in translating and refining this feedback text, aiming to facilitate a faster understanding and resolution of the issue by your team.

A  Player

**Comment by Noaaan** [comment]
Currently the April Fools easter egg hard replaces the text instead of translation keys. As such the lines are unfortunately not translated. 
Now I will note that the translations currently last a bit longer than a single day, see my comment on #237 - it lasts through the first week of April. You can disable this behavior in your config (look for the `disableFunny` option), and it should revert the configuration back to normal.

**Comment by c1390818629** [comment]
Thanks for your reply, I just happened to find that the translation has been restored to normal today. I apologize for troubling your team.
Thank you for creating high-quality mods for the players！！
