### ISSUE TITLE
April fools items not reverted to normal names after april fools

### ISSUE THREAD

**Issue by CassieRoseZA** [Noaaan/MythicMetals#237]
![image](https://github.com/Noaaan/MythicMetals/assets/13422754/aa58c7d3-275d-402b-b1f2-d041acf0d957)
for some odd reason its still showing me this when i look for durasteel as april fools is finished

**Comment by Noaaan** [comment]
The April Fools stuff lasts for the first week of April, meaning it can last between 1-7 days depending on the year. Coincidentally, this years April 1st was on a Monday, and as such it lasts throughout this week.

**Comment by CassieRoseZA** [comment]
ah okay Thanks
