### ISSUE TITLE
[Bug] Regrowth effect not working on modded weapons

### ISSUE THREAD

**Issue by noodlenoir** [Noaaan/MythicMetals#240]
I currently have a promethium katana, using the mod Simply Swords. No matter how long it is in my active hand, it does not regain durability. This problem does not extend to my other promethium gear, such as my armor. My guess is that this bug has to do with the weapon being a unique modded one. 
I'm unsure if the bug is with Mythic Metals or Simply Swords, so I will be opening this issue under both.

**Comment by antuar-ramos** [comment]
Can confirm this, using another weapon from Simply Swords on minecraft 1.20.1 (mod version 0.19.7). Tools made from prometheum do regenerate, but the rapier weapon does not no matter if where it is in my inventory

**Comment by Noaaan** [comment]
I don't blame Sweeney for this, as the Prometheum handling and Ability "API" is very poor. 
With the final release of 1.20.1 I am simplifying the code for this, which should make it much easier to implement the changes required for the Prometheum tools.

**Comment by Noaaan** [comment]
Generally the system for auto repair should be way better now. For both 1.20 and 1.21 there are better systems in place for this, which are documented in the PATCHNOTES.md file. 

Specifically for 1.21 feel free to pass this to any mod developers which can add compat: https://github.com/Noaaan/MythicMetals/blob/1.21/PATCHNOTES.md#ability-changes
