### ISSUE TITLE
client crashes when leaving a server (1.21)

### ISSUE THREAD

**Issue by MrSn0wy** [Noaaan/MythicMetals#249]
Heya,
i've found a bug that crashes the client when you leave a server that also has mythic metals installed.
I know that the 1.21 version of the mod is still in alpha but still wanted to let you know.

Here is the game's crash log:
[log.txt](https://github.com/user-attachments/files/16101302/silly_error.txt)

**Comment by Noaaan** [comment]
Duplicate of https://github.com/wisp-forest/alloy-forgery/issues/139
