### ISSUE TITLE
Cannot See Recipes

### ISSUE THREAD

**Issue by dgiordano2006** [Noaaan/MythicMetals#255]
Hello, I have downloaded Mythic Metals For Minecraft 1.19.4, however I cannot see any of the recipes in the crafting table or in the mod JEI, I tried running it with Mythic Metals alone however I ran into the same issue, it only worked for minecraft 1.19.2, I was wondering if there was a fix to this? I can only see ingot crafting, not weapons/tools crafting. Any help would be greatly apricated, I love the mod and just wished I can see the recipes, thank you :DDD

**Comment by Noaaan** [comment]
JEI is currently not supported. Please see https://wiki.mythicmetals.com/faq/#how-do-i-craft-x for alternatives
