### ISSUE TITLE
[1.20.1] Mythic Metals 0.19.9 crash server on startup

### ISSUE THREAD

**Issue by Zimnyte** [Noaaan/MythicMetals#257]
Crashes on startup. Might be some conflict with other mods but I honestly couldn't find any. Works on singe player with no issues.

Mythic Metals - 0.19.9
Fabric API 0.92.2+1.20.1
Fabric Loader 0.15.11
Java - zulu17.50.19-ca-jdk17.0.11

https://mclo.gs/HBWosZX#L997

**Comment by Noaaan** [comment]
This is a know incompat between sushi-lib and owo-lib. Remove Particular (this mod is client-only, and should not be loaded on a server), and any other mod that requires the library from your server

**Comment by Zimnyte** [comment]
Thanks. It worked 👍
