### ISSUE TITLE
Future compatibility with alloy-forgery

### ISSUE THREAD

**Issue by PixelatedBruh** [Noaaan/MythicMetals#26]
<Enhancement>

Hey it is me again and I think this might be something to at least just look at when fabric fluid api comes into play.

https://www.curseforge.com/minecraft/mc-mods/alloy-forgery

Just wanted to hear your thoughts on this.

**Comment by Noaaan** [comment]
I would recommend checking out the patch notes. This mod was pretty much created FOR Mythic Metals, to replace the old alloy system.

**Comment by PixelatedBruh** [comment]
oh I'm an idiot sorry.

**Comment by Noaaan** [comment]
No worries! In fact, im thankful you took the time suggest it. I am always open to improve the mod in any way possible. Feel free to throw some more suggestions in the future!
