### ISSUE TITLE
Mythic metal armors cannot have tiers from TieredZ mod

### ISSUE THREAD

**Issue by yagow1337** [Noaaan/MythicMetals#263]
Auto-explanatory title, armors from mythic metals cannot be modified, i reported the issue on the TieredZ modrinth page, and the creator said that Mythic Metal's armors aren't vanilla-tagged

Tools can be tiered, probably have the tags

![image](https://github.com/user-attachments/assets/558cc55a-17d2-42ca-8895-eefdfd71157a)

**Comment by Noaaan** [comment]
This should be resolved for the next version of Mythic Metals

**Comment by Noaaan** [comment]
Should be resolved as of 0.20.2
