### ISSUE TITLE
Stormyx Block Carmot Staff continuously crashes the game

### ISSUE THREAD

**Issue by Iggoreum** [Noaaan/MythicMetals#264]
I've been experimenting with the Stormyx Carmot Staff, and it seems to crash whenever any arrow collides with it. First crash was from a pillager, second one I tried with a skeleton, but the game crashed even before it nocked an arrow, which leads me to believe it was the arrow entity on the ground.

Fireballs were being deflected without issue, also.

[crash-2024-09-25_23.31.53-client.txt](https://github.com/user-attachments/files/17141887/crash-2024-09-25_23.31.53-client.txt)

[crash-2024-09-25_23.21.38-client.txt](https://github.com/user-attachments/files/17141853/crash-2024-09-25_23.21.38-client.txt)

**Comment by Noaaan** [comment]
For some reason Inventory Tabs seems to be crashing here. Do these still happen if you disable that mod?

**Comment by Iggoreum** [comment]
Yes, I've tried it without now. However the game did not crash this time, as Neruina prevented it whilst calling it a Ticking Entity Exception.

Edit: found informations in the log below
[latest.log](https://github.com/user-attachments/files/17155481/latest.log)
I've also found out it happens with splash potions from witches, and that wind charges and the musket balls from the musket mod interact as intended with it.

**Comment by Noaaan** [comment]
Considering this is a client crash, I suspect there being some mod compat going on here. I am not able to reproduce the second crash, which seems related to particles.
I have found one potential issues with arrows, which should be fixed as of the commit above

**Comment by Noaaan** [comment]
This is now released as 0.20.2. Could you try out this version and see if you still experience crashes?

**Comment by Iggoreum** [comment]
I've tested it, works fine with modded and vanilla projectiles now, thanks for the help!
