### ISSUE TITLE
No aquarium is generated.

### ISSUE THREAD

**Issue by Lymno** [Noaaan/MythicMetals#265]
I use the Terralith mod and the Mythic Metals mod, and other minerals generate fine. But I can't find aquarium. Neither the ocean nor the river can generate any aquarium.  The mod version is 0.20.1. Game version is 1.21.1.

**Comment by Noaaan** [comment]
I have been receiving reports like this i  Discord without being able to reproduce it. Terralith might be doing something with the compat. I will investigate this
