### ISSUE TITLE
Cient and server crashes unpredictably when using star platinum arrows 

### ISSUE THREAD

**Issue by Aesthir** [Noaaan/MythicMetals#266]
I was shooting star platinunm arrows from a modded crossbow when my game crashed unexpectedky, taking the server down as well. I do not konw how it happened, or whether MythicMetals was responsible. Feel free to ask any question or request any information that may help you pinpoint the cause. For now, here's the crash report:

[crash-2024-09-28_01.07.17-server.txt](https://github.com/user-attachments/files/17177414/crash-2024-09-28_01.07.17-server.txt)

**Comment by Noaaan** [comment]
What modded crossbow? I haven't been able to reproduce this yet, and I suspect the issue stems from it

**Comment by Noaaan** [comment]
Disregard that - there seems to be a specific issue when shooting Star Plat arrows with a Crossbow
