### ISSUE TITLE
Dont know how to get dust 

### ISSUE THREAD

**Issue by Nev0ka** [Noaaan/MythicMetals#29]
Hey
Me and my friends are playing with your mod pack and we are trying to turn ores in to dust, we have tried everything, and we cannot get dust.
Even the Alloy Forge don't do anything.

**Comment by Noaaan** [comment]
Dusts are currently not obtainable in basic Mythic Metals. They are a compatability item, and the only way to get them is by crushing ores with other mods. 
Currently TechReborn, Modern Industrialization,  and Mechanix are supported. If you have any mods other tham these that do have a grinder, or something similar, let know!
