### ISSUE TITLE
A solution to Mythic Metals having 4 tabs in the creative inventory.

### ISSUE THREAD

**Issue by K0-RR** [Noaaan/MythicMetals#30]
Mods Biome Makeover and Draylar's Battle Towers use a system shown on these screenshots. Can Mythic Metals have something like this too? Both these mods are open source so maybe you can borrow some code?

![image](https://user-images.githubusercontent.com/43277609/110205856-be5fee80-7e7a-11eb-80d5-9dbb0c779947.png)

![image](https://user-images.githubusercontent.com/43277609/110205860-c61f9300-7e7a-11eb-89aa-931ec68b2c02.png)

**Comment by Noaaan** [comment]
Interesting idea, I will look into it

**Comment by Azagwen** [comment]
After investigation, it seems one must have copied from the other here, as both systems are almost identical.
Implementing this seems easy but my first attempt failed on my end

**Comment by Noaaan** [comment]
Not sure why you are commenting this on my issue, lol.  
Yes, from the issues above the implementation originates from Biome Makeover, and was re-implemented into Drayars Battle Tower, since the code is MIT. You can see Draylars implementation here: https://github.com/Draylar/battle-towers/blob/1.16.2/src/main/java/draylar/battletowers/group/BattleTowersItemGroup.java

**Comment by Azagwen** [comment]
> Not sure why you are commenting this on my issue, lol.
> Yes, from the issues above the implementation originates from Biome Makeover, and was re-implemented into Drayars Battle Tower, since the code is MIT. You can see Draylars implementation here: https://github.com/Draylar/battle-towers/blob/1.16.2/src/main/java/draylar/battletowers/group/BattleTowersItemGroup.java

Because there's nothing in mine lol, so I thought I'd reply there. could also help other modders that will get your issue quoted in their own issues, who knows :D

**Comment by Azagwen** [comment]
I just finished implementing it, so if you want now you have a third mod to look at for references.
here : https://github.com/Azagwen/ATBYW/tree/dev/src/main/java/net/azagwen/atbyw/group

Wish you luck if you decide to implement it, it shouldn't be too hard but some of the stuff those two mods given as exampels had was not working for me for some reason, so I had to change stuff around.
