### ISSUE TITLE
Could you please change the Starrite ore texture?

### ISSUE THREAD

**Issue by K0-RR** [Noaaan/MythicMetals#31]
To be honest, the texture looks childish, especially when compared to the superior-looking ones like unobtainium (so it does not generate?) carmot, mythril, quadrillum. Starrite can use one of these textures if not used by a few more ores already.
I can create a new texture based on the new vanilla ores textures from 1.17 snapshots if you would be interested.

Btw tantalite ore is nearly invisible when spawned in the neighborhood of the stone. The texture is good but the colors could be different.
![image](https://user-images.githubusercontent.com/43277609/110206190-8d80b900-7e7c-11eb-9c7d-bac3fa2ba8bb.png)

**Comment by Noaaan** [comment]
Textures for ores are currently being worked on by Tector, but due to personal issues he had to step away for a while.
If you want to contribute a new texture I would be very grateful! Starrite being "childish" is an interesting thought considering it is mainly a placeholder texture made from downscaling a star.

Tantalite is also subject to change, as I personally hate the current colour of the ore.

**Comment by K0-RR** [comment]
I noticed that Stormyx uses the same texture as Gems from More Gems mod. Maybe Stormyx texture could be rotated by 90/270 or 180 degrees? Oh, they could be mirrored vertically and horizontally too.
![image](https://user-images.githubusercontent.com/43277609/110225532-9c9c5100-7ee6-11eb-847b-0ed784241241.png)

**Comment by K0-RR** [comment]
Also, what about using official (from 1.17 snapshots) copper texture?
![image](https://user-images.githubusercontent.com/43277609/110225605-72975e80-7ee7-11eb-8e1e-0bac2c2e8d1b.png)

**Comment by K0-RR** [comment]
Closing because too cluttered.

**Comment by Noaaan** [comment]
Stormyx actually uses the emerald ore texture. It should mostly be fine considering it is in the nether.
I have considered refactoring some of the new ore textures into Mythic Metals. We'll see which ones make it through.

**Comment by Noaaan** [comment]
In coppers case it will plainly be removed in the 1.17 version as it is not needed at all. The block textures will be updated to reflect this.
