### ISSUE TITLE
Unable to build from source - gradle files in .gitignore.

### ISSUE THREAD

**Issue by K0-RR** [Noaaan/MythicMetals#32]
Or at least I think this is a reason they are not downloading when I click Download ZIP on the Code tab.

**Comment by Noaaan** [comment]
The .gradle folder is not supposed to be included in the repository since it is generated upon running gradlew build.
I just tested this by downloading the zip from MASTER and running it, builds like expected.

**Comment by K0-RR** [comment]
I'm not talking about gradle folder which btw downloads fine
Wait what I downloaded it again and now the file size is 1,42 MB and also it contains more files like the mentioned gradlew. Guess my download was interrupted or something but how then Chrome marked the download as completed?
