### ISSUE TITLE
Add support for Patchouli for checking alloys recipes.

### ISSUE THREAD

**Issue by K0-RR** [Noaaan/MythicMetals#33]
Currently, users need to read your wiki, would be nice if they could read it in-game.
https://github.com/LordDeatHunter/Alloy-Forgery/issues/6

**Comment by Noaaan** [comment]
Thanks for opening a suggestion for this. I am planning to add this later on, but for now I have to focus on writing the Wiki itself.

**Comment by Noaaan** [comment]
You are now able to see recipes in game as of Alloy Forgery 1.0.8 through REI.
