### ISSUE TITLE
modded ores not spawning in the overworld

### ISSUE THREAD

**Issue by Hominator01** [Noaaan/MythicMetals#35]
i dont seem to have any of the modded ores in survival but i have them in creative is there something im doing wrong for me to not have any of the ores to spawn naturally

 these are the mods i have on and they all seem to work properly except for mythic metals

advanced xray fabric

animal feeding trough

basic nether ores

biomes you go

castle dungeons

cave biomes

cloth config 

crusade mod

fabric api 

mythic metals

optifabric 

optifine

piglib

roughly enough items

wraith alloy forgery

**Comment by Noaaan** [comment]
Could you write up what versions of the mods you are using?

**Comment by Noaaan** [comment]
I am currently un-able to re-produce this issue using these mods:  
Mods:
  [✔️] animal_feeding_trough-1.0.0
  [✔️] BasicNetherOres-1.16.4-5.4.0-Fabric
  [✔️] byg-1.1.3
  [✔️] castle_dungeons-2.2-1.16.5-fabric
  [✔️] cavebiomes-0.6.2
  [✔️] cloth-config-4.11.14-fabric
  [✔️] crusade-mod-1.2.0
  [✔️] fabric-api-0.31.0+1.16
  [✔️] mythicmetals-0.9.9
  [✔️] piglib-1.0.2+1.16
  [✔️] RoughlyEnoughItems-5.8.10
  [✔️] wraith-alloy_forgery-1.0.7

**Comment by Hominator01** [comment]
[**_Same_**]animal feeding trough-1.0.0
[**_Different_**]basic nether ores-1.16.5-5.5.0-fabric
[**_Different_**] byg-1.1.5
[**_Same_**] castle dungeons-2.2-1.16.5-fabric
[**_Same_**] cave biomes-0.6.2
[**_Same_**] cloth config-4.11.14
[**_Same_**] crusade mod-1.2.0
[**_Same_**] fabric api-0.31.0+1.16
[**_Same_**] mythicmetals-0.9.9
[**_Different_**] piglib-1.0.3+1.16.5
[**_Different_**] RoughlyEnoughItems-5.11.185
[**_Same_**] wraith alloy forgery-1.0.7

**Comment by Hominator01** [comment]
Is it possible its because i made a new world first then added mods afterword

**Comment by Noaaan** [comment]
Oh if you added the mod in *afterwards* then the ores will not have generated. Minecraft does not re-generate anything, so you will only find the ores in new chunks.

**Comment by Hominator01** [comment]
ah ok i see thanks for that information i kept trying to look for solutions and nothing came up so i was confused i didnt know that minecraft didnt re-generate things. Thanks for everything.

**Comment by Hominator01** [comment]
BTW i dont want to delete my world and start from scratch. By finding ores in new chunks does that mean they are in the world just far from my location or not in the world at all. Im sorry im not that good in terminology

**Comment by Hominator01** [comment]
Ah never mind i figured it out i looked it up in google thanks for everything and have a good day
