### ISSUE TITLE
Aetherium & Starrite config mixup

### ISSUE THREAD

**Issue by hugeblank** [Noaaan/MythicMetals#39]
Just found this while seeing how aetherium is distributed. `oreAetherium` & `oreStarrite` are swapped with where their conditionals are to check if they're enabled in config.

https://github.com/Noaaan/MythicMetals/blob/afd9a1d179fa9e2b7e07599960085f1b87ea636c/src/main/java/nourl/mythicmetals/world/OreGenerator.java#L203-L208

**Comment by Noaaan** [comment]
Thanks for pointing that out. I will fix this for next release.
