### ISSUE TITLE
Unobtainium ore isnt being generated in my world 1.17

### ISSUE THREAD

**Issue by campbebj** [Noaaan/MythicMetals#41]
Hey im using mythic metals and having trouble finding unobtainium ore in my world.
im using the 0.10.0 snapshot A version of the mod and ive even search my world with an NBT editor, 
My first suspision is it has to do with me having -64 being the bedrock layer in my world, but im not 100% sure if that would matter. i tried reading through the code and didnt see anything that suggested any unique spawning conditions other than to search at level 7, so i tried at level "7" and at 7 levels above bedrock, both with no luck, is there any unique spawning condition i might be missing, or any known mod incompatabilities. i havent had issues with any other ore so far.

im going to be installing snapshot B and trying to generate some new chucks to see if that has any effect.

**Comment by Noaaan** [comment]
It sounds like you are looking at the code for 1.16. The code used in the 0.10+ snapshots are all on the 1.17 branch. The average height has changed dramatically, in a way that benefits having the world with an extended bottom. The current best average height to find it is roughly -24. 

Unobtainium *does* have some special spawn conditions, mainly having a high chance of being discarded on air, and having a chance to be ignored on spawn.

Currently the latest unreleased build is Snapshot C, which has upped the chance of finding unobtainium somewhat.

**Comment by campbebj** [comment]
ok ill pull it down and build it.

**Comment by campbebj** [comment]
I was able to find some using snapshot C, however the loot table dropped nothing and it looks like the diamond pick should have been sufficient based on the mining level.

**Comment by Noaaan** [comment]
Mining level 4 requires at least netherite to be mined. Hallowed components (adamantite, mythril, orichalcum), Hallowed itself, Palladium, or Aetherium are the earliest materials from MM that can mine it

**Comment by campbebj** [comment]
I must have misread it as 3 in the code, is there a way to make it break
slower for diamond to suggest to the player they shouldn't go forward?
-ben

**Comment by Noaaan** [comment]
It already has double the hardness of diamond ore, where the deepslate variant is even harder. I will tweak the deepslate variant slightly, but it seems a bit unreasonable to have an even higher hardness.

The GitHub player could not play this compressed gif, replaced it:

https://user-images.githubusercontent.com/4163353/132985253-dae12ebd-e1d4-4cca-a190-bb96b5d403df.mp4

**Comment by Noaaan** [comment]
I want to note though that I have discovered an issue with the snapshots and using the new `applyChance` range configuration. It worked differently from what I expected and has made unobtainium, well, practically unobtainable.
I will revert this for the next build as it is not quite what I had in mind when using this.

**Comment by elite092** [comment]
> Mining level 4 requires at least netherite to be mined. Hallowed components (adamantite, mythril, orichalcum), Hallowed itself, Palladium, or Aetherium are the earliest materials from MM that can mine it

I know this is an old post, but all I could find for mining level for unobtainium. You're saying we need mining level 4 to mine it, and I'm wondering  - does the Legendary Banglum Pickaxe meets this requirement? It's the fastest way to mine in the overworld afaik but I want to make sure I'm not blowing up unobtainium.

**Comment by Noaaan** [comment]
The Legendary Banglum Pickaxe is not able to mine it, and it will in fact not destroy it either, since it is outside its mining level range. 
Please do not ask these kinds of questions on old issues, I would rather you ask in the [Wraith Coding Sesh Discord server](https://discord.gg/69cKvQWScC), or open a new issue. 


> I know this is an old post, but all I could find for mining level for unobtainium. You're saying we need mining level 4 to mine it, and I'm wondering - does the Legendary Banglum Pickaxe meets this requirement? It's the fastest way to mine in the overworld afaik but I want to make sure I'm not blowing up unobtainium.
