### ISSUE TITLE
No recipes for Deepslate unobtainium ore

### ISSUE THREAD

**Issue by campbebj** [Noaaan/MythicMetals#42]
i mined some deepslate unobtainium ore and was unable to process it and REI suggested no recipes.

**Comment by Noaaan** [comment]
I am presuming you are thinking around using Silk Touch to pick up the ore. I have implemented some recipes through tags with this, so I am not sure exactly what you mean by this. 
I do see that there are some missing recipes though, I will correct this today.
![image](https://user-images.githubusercontent.com/4163353/133115097-66a61c69-7b26-455e-8aea-c9e03f6f8c76.png)

**Comment by Noaaan** [comment]
Man I screwed up those commits. Added the unobtainium ores tag to recipes where it applies.
