### ISSUE TITLE
LevelZ Compatibility 

### ISSUE THREAD

**Issue by Dalethium** [Noaaan/MythicMetals#44]
[message.txt](https://github.com/Noaaan/MythicMetals/files/7404109/message.txt)

https://github.com/Noaaan/MythicMetals/blob/1.17/src/main/java/nourl/mythicmetals/armor/ArmorMaterials.java#L142

LevelZ tries to reference the method above but it is clientside only, so when you equip levelZ gear you crash. Discussed on discord, but I figured I'd open an official issue here :)

**Comment by Noaaan** [comment]
Issue is fixed, will be pushed once I finish up the rest of the stuff I am working on 👍
