### ISSUE TITLE
Osmium tools and sword are busted

### ISSUE THREAD

**Issue by saltyseadoggo** [Noaaan/MythicMetals#45]
When I booted up a testing world to check out this mod, osmium is the first ore I noticed underground, and I went to investigate what could be done with it, finding that it makes ridiculously powerful tools and swords for how common the stuff is. Some notes:
- The osmium sword deals the same damage as a netherite sword (8), has more durability (2048 versus netherite's 2031), and swings faster (1.5 attack speed versus netherite's 1.6). With this mod, there is no reason to grind for netherite when you can get the superior osmium extremely quickly with just an iron pickaxe.
- The osmium pickaxe mines blocks as fast as an iron pickaxe, but it can still mine obsidian.

I admittedly don't understand what osmium's intended niche is. If it's meant to be more a more durable but less effective alternative to diamond, judging by the tools having the same digging speed as iron, then maybe make it rarer and drop the sword's damage to 6, like iron? Otherwise, idk how to rebalance it. This issue can be a place to discuss, I guess.

**Comment by Noaaan** [comment]
Thank you for opening this issue. Osmium accidentally had Orichalcum's tool stats. 
This will be hotfixed tomorrow.
