### ISSUE TITLE
Silver ingot issue

### ISSUE THREAD

**Issue by Oscienet** [Noaaan/MythicMetals#5]
In 0.9.4 silver ingot can be smelled to the same ingot, without getting exp from this
I think the problem in tags, because in 0.9.3 it doesn't work
Here is the screenshot from the REI btw
![image](https://user-images.githubusercontent.com/74426790/99107527-0c649400-25f7-11eb-8f86-4a2514ef0bcd.png)

**Comment by Noaaan** [comment]
Hello!
Thank you for raising this issue! I have found the problem, and it is indeed related to the tags.
I renamed the files wrongly, meaning silver ores and silver ingots switched places.
I will fix this as soon as possible in an upcoming update. Thanks for posting the issue!
![image](https://user-images.githubusercontent.com/4163353/99115626-040a5a00-25f3-11eb-9671-2c0b08748c75.png)

**Comment by Oscienet** [comment]
There is a problem with electrum [alloy] too. The it's texture (and recipe of electrum irl) is gold+silver, but recipe used in your mod is a gold+zinc. 
![image](https://user-images.githubusercontent.com/74426790/99150483-fb269080-26a5-11eb-8a87-b43461b83796.png)
(Oh, and a little question: can i translate MythicMetalls to russian lang..?)

**Comment by Noaaan** [comment]
Yeah, feel free to make a translation. Submit it as a pull request or upload the file as an issue, and i will include it
