### ISSUE TITLE
Server Crash on version 0.11.1

### ISSUE THREAD

**Issue by CoruptedUsername** [Noaaan/MythicMetals#55]
I was updating my minecraft server, and it would crash approximately 10 seconds after I started loading it. After slowly trying to load it with different subsets of the mod list, I found that with every mod other than Mythic Metals installed, it would correctly load. I tried going from version 0.11.1 to 0.11.0, and it stopped crashing
[2022-01-06-7.log](https://github.com/Noaaan/MythicMetals/files/7826017/2022-01-06-7.log)

**Comment by Noaaan** [comment]
Will fix this soon in a future release
