### ISSUE TITLE
ERROR: Couldn't read tag list mythicmetals:*_mining_level

### ISSUE THREAD

**Issue by silentnyte** [Noaaan/MythicMetals#56]
On a dedicated server in the log I see this error for all the *_mining_level.json

[Worker-Main-2/ERROR]: Couldn't read tag list mythicmetals:diamond_mining_level from mythicmetals:tags/blocks/diamond_mining_level.json in data pack Mythic Metals
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $

Fabric 1.17.1
loader 0.12.12 
MythicMetals 0.10.2-fix

Full log https://pastebin.com/f2RPWS7b

**Comment by Noaaan** [comment]
It seems that this jar has experienced a slight corruption during build, which caused it to include empty mining level tags that are exclusive in 1.18.
The tags are empty, are not used and do not do anything. Your server should be fine, but I will upload a hotfix which excludes these tags.

**Comment by silentnyte** [comment]
That was a quick resolution!

**Comment by Noaaan** [comment]
You caught me on a good time as I was working on MM 😅  
I just released a fix on CF/MR/GH. Make sure you are using it and the log-spam should disappear.
