### ISSUE TITLE
Crash with Harvest Scythes - Fabric 1.18.1

### ISSUE THREAD

**Issue by xR4YM0ND** [Noaaan/MythicMetals#59]
[latest.log](https://gist.github.com/SpigotDE/40625ec0b841d01d3b3b59e8c4842fe6)

**Comment by xR4YM0ND** [comment]
The game crashed whilst initializing game
Error: java.lang.NoSuchFieldError: STEEL
Exit-Code: -1

**Comment by xR4YM0ND** [comment]
Modpack used : [The Progressor](https://www.curseforge.com/minecraft/modpacks/the-progressor)
Updated all mods

**Comment by xR4YM0ND** [comment]
kk thx

**Comment by Noaaan** [comment]
Fixed in HarvestScythes 2.4.1
