### ISSUE TITLE
Move DefaultRegistryMixin identifiers to separate class

### ISSUE THREAD

**Issue by Qendolin** [Noaaan/MythicMetals#61]
These identifiers pollute every instance of DefaultedRegistry which are quite a lot.
https://github.com/Noaaan/MythicMetals/blob/e1bf9fd4efc800fb16a54fd0671224dc1379bb6a/src/main/java/nourl/mythicmetals/mixin/DefaultedRegistryMixin.java#L17

This does not cause any issues right now but it is very annoying seeing all those fields in my IDE when debugging. 
Even worse they are not private.

![image](https://user-images.githubusercontent.com/32160662/151617553-71806748-aab2-492c-baa1-390218708742.png)

**Comment by Noaaan** [comment]
Should hopefully be fixed in latest commit. If you could try it out I would make a release if it seems good

**Comment by Qendolin** [comment]
I don't really wanna download the source and setup the project, can you give me a jar?

**Comment by Noaaan** [comment]
No problem, here you go: [mythicmetals-0.11.4.zip](https://github.com/Noaaan/MythicMetals/files/7965000/mythicmetals-0.11.4.zip)

**Comment by Qendolin** [comment]
Just tried it out, and it's fixed

**Comment by Noaaan** [comment]
Fixed and released as of 0.11.4
