### ISSUE TITLE
I translated this mod into Chinese Simplified

### ISSUE THREAD

**Issue by clarenre** [Noaaan/MythicMetals#62]
some ores are too hard to translate because there is no accurate translations for them. So I translate them into that sound like in English.By the way ,I don't know much about the tone in English,If I say some impolite word,I'm sorry for that.just upzip it because github can't upload .json. It's for Minecraft 1.18.1, 0.11.4
[zh_cn.zip](https://github.com/Noaaan/MythicMetals/files/8009374/zh_cn.zip)

**Comment by ghost** [comment]
froge is not frog (x

**Comment by clarenre** [comment]
But in fact, you can't see it in the game, so I don't know what it should be translated into

**Comment by ghost** [comment]
This is not very important, don’t mind~

**Comment by Noaaan** [comment]
As mentioned in the link pull request I am working on a more accurate translation for Chinese. Because of this I will re-make this issue until it is finished.
