### ISSUE TITLE
Incompatable with Cosmetic Armour?

### ISSUE THREAD

**Issue by Zunwolf1896** [Noaaan/MythicMetals#72]
Hey, great mod, but a couple of my players found an issue last night, they crafted a Hallowed Helmet each, (like 10 minutes between them) put the helmet on and at another point used the Cosmetic Armour slot from this mod (https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric) to put a different kind of helmet on. This caused them to crash.

I have not experienced this myself so asked them to explain what  happened:

"Wearing the hallowed helmet
And armor in a vanity slot
At the same time
It crashes you if you open your inventory, click f5 and it crashes people in the area
Me and neon both had the same problem but with different armor, I think it’s just bugged if you combine the hallowed in your main armor slot with any armor in your vanity slot
You just don’t crash until your player is loaded
So opening crafting tables works"

Not sure if I should be reporting this here or with the other mod - sorry if it should be the other one. 

I am using the latest version of both plugins

**Comment by Noaaan** [comment]
I am not able to test this right now, but if you could provide a crash-report that would be very helpful

**Comment by Noaaan** [comment]
Looking deeper into this issue it is very similar to https://github.com/DaFuqs/Spectrum/issues/27

The main issue here seems to be related to the code of Cosmetic Armor itself. They have not pushed their latest code yet so pinpointing it isn't the easiest, but I think it is likely related to their [HeadFeatureRendererMixin] (https://github.com/apace100/cosmetic-armor/blob/1.18/src/main/java/io/github/apace100/cosmetic_armor/mixin/MixinCosmeticHeadVisibility.java) not accepting custom armor rendering, which could cause a crash. 

When testing this I was not able to re-produce this crash at all, with all of my custom armor rendering (Cosmetic Armor 1.2.1 and Mythic Metals 0.12.1). Are you sure it was my armor items that crashed?

**Comment by Zunwolf1896** [comment]
Two more players have been having issues, I managed to get them to give me the crash reports

[crash-2022-03-17_15.59.58-client.txt](https://github.com/Noaaan/MythicMetals/files/8287949/crash-2022-03-17_15.59.58-client.txt)
[crashreportTheo.txt](https://github.com/Noaaan/MythicMetals/files/8287950/crashreportTheo.txt)

**Comment by Noaaan** [comment]
What armor items are your players wearing exactly?

**Comment by Zunwolf1896** [comment]
One player says:
The one that made me crash was a breastplate made of the hollowed stuff. And I think I had a normal iron one in the seeing one (idk how to describe it) that I had forgotten to take off 

The other player says:
it was when i switched to hallowed armour
seems like it was bugging out if you have cosmetic over it
so i had normal diamond on and switched my leggings and chestplate to hallowed
when i put on the chestplate it crashed
no enchants
i think its the fact that i had cosmetic armour on
just leather
but from the crash report at the time it seemed like that was it

**Comment by Noaaan** [comment]
This is a very weird issue. Considering the amount of issues opening up on Cosmetic Armors repo I would guess it is something on their end. I will open an issue there to get to the bottom of this.
