### ISSUE TITLE
Crashed The Game

### ISSUE THREAD

**Issue by Akane-N** [Noaaan/MythicMetals#73]
Hello, I'm currently making a modpack and just added mythic metals to it, everything was working for a short time then it crashed the game, I have the crash report, I'm still new to using mods and making packs so I don't fully know how to read these to figure out what the issue is sorry.
[crash-2022-04-14_00.51.43-client.txt](https://github.com/Noaaan/MythicMetals/files/8486965/crash-2022-04-14_00.51.43-client.txt)

**Comment by Noaaan** [comment]
This is an issue with Alloy Forgery. The fix for this is ready, so I will draft up a release for it

**Comment by Noaaan** [comment]
This issue has been fixed in Alloy-Forgery 2.0.12, please update to this version
