### ISSUE TITLE
Still crashing game, worse now

### ISSUE THREAD

**Issue by Akane-N** [Noaaan/MythicMetals#74]
Hi sorry to bug you again but its still crashing the game, except now it crashes when I open my inventory, here's the crash report

[crash-2022-04-14_20.19.36-client.txt](https://github.com/Noaaan/MythicMetals/files/8493432/crash-2022-04-14_20.19.36-client.txt)

**Comment by Noaaan** [comment]
Fixed in [Alloy Forgery 2.0.13](https://github.com/LordDeatHunter/Alloy-Forgery/releases/tag/2.0.13%2B1.18)
