### ISSUE TITLE
anvil duping

### ISSUE THREAD

**Issue by zerevoidd** [Noaaan/MythicMetals#76]
mining any mythicmetals anvil gives you 2 instead of 1

**Comment by LargerManZ** [comment]
bump

**Comment by zerevoidd** [comment]
what

**Comment by Noaaan** [comment]
Despite multiple people claiming this I am not able to re-produce it. Could you provide me more information about what mod(s) you are using with Mythic Metals? A log would be sufficient

**Comment by LargerManZ** [comment]
It might be a problem with the modpack, because I'm using a large one.

**Comment by Noaaan** [comment]
Bumping this. I am not able to re-produce it. Please provide a log containing your mod-lists

**Comment by Noaaan** [comment]
Closing this as its not re-producible. It is likely a compat issue, but I am yet to uncover it. Feel free to re-open with more information on what could be causing it.
