### ISSUE TITLE
Missing Bronze Ore?

### ISSUE THREAD

**Issue by ardissaps** [Noaaan/MythicMetals#77]
Is there any plan adding bronze ore (to craft already there bronze equipment)?

Missing item :
https://imgur.com/a/HsNDyhM

**Comment by Noaaan** [comment]
I would recommend reading up on these, as Bronze is obtainable in Mythic Metals.

https://en.wikipedia.org/wiki/Bronze
https://install-roughly-enough-items-to-use-alloy-forgery.xyz/

**Comment by ardissaps** [comment]
> I would recommend reading up on these, as Bronze is obtainable in Mythic Metals.
> 
> https://en.wikipedia.org/wiki/Bronze
> https://install-roughly-enough-items-to-use-alloy-forgery.xyz/

Oh i see, thx!
