### ISSUE TITLE
Any Plan Adding Steel (white) Armor?

### ISSUE THREAD

**Issue by ardissaps** [Noaaan/MythicMetals#78]
Any Plan Adding Steel (white) Armor?

**Comment by Noaaan** [comment]
What do you mean by this? Regarding steel armor I would see commit 386e5347c5c40ddec5925a3d86753fabeb895592.

**Comment by Noaaan** [comment]
If you are talking about adding white-coloured steel armor, then this is not something I want to do in base Mythic Metals.
