### ISSUE TITLE
Storage blocks issue

### ISSUE THREAD

**Issue by Oscienet** [Noaaan/MythicMetals#8]
All storage blocks' harvest/mining level set as 3, that at many cases different from same ore's harvest/mining level
Here is the screenshots with silver as the example
![2020-11-16_05 10 34](https://user-images.githubusercontent.com/74426790/99205632-2bffe600-27ca-11eb-9296-a8330b1e833e.png)
![image](https://user-images.githubusercontent.com/74426790/99204604-3ff61880-27c7-11eb-953d-7c3fc520b907.png)
(i already checked: it isn't a hwyla's/cimtb's bug, btw)

**Comment by Noaaan** [comment]
Yeah I am aware of this!
I havent had time to test out what mining levels I should use for them yet, hence why all of them have assigned the same placeholder value of 3.
This is what I am currently working on, and I will push an update for this later this week.

**Comment by Noaaan** [comment]
This has been implemented in the upcoming 0.9.6 release. Thank you for raising this issue!
