### ISSUE TITLE
Mythic Metals Platinum not showing in REI??

### ISSUE THREAD

**Issue by StockiesLad** [Noaaan/MythicMetals#80]
No idea

**Comment by Noaaan** [comment]
Is platinum ore generation disabled? When disabled all Platinum items from MM are automatically hidden in REI, since they cannot be obtained normally anymore

**Comment by StockiesLad** [comment]
yes it is, although I want the block to be shown

**Comment by StockiesLad** [comment]
as well as the armor. I disabled the world gen so that I can use other ores

**Comment by Noaaan** [comment]
I might look into a better solution for the REI hiding, though I do want to point out Platinum does not have a tool & armor set.
If *Star Platinum* gear is being hidden by this, then that is a bug, and will be fixed.

**Comment by StockiesLad** [comment]
Well, I can use kubejs worldgen events to circumvent this. But for now, this technically isnt a bug so ill close it
