### ISSUE TITLE
Item Texture Suggestion

### ISSUE THREAD

**Issue by ardissaps** [Noaaan/MythicMetals#82]
Would you like to tweak item to similiar style as [Stoneborn](https://www.curseforge.com/minecraft/texture-packs/stoneborn-dwarven-fantasy-inspired-gear-overhaul/screenshots)? Thank you very much.

**Comment by Noaaan** [comment]
Stoneborn is an interesting resourcepack. I do not want to base the entire mod around a medieval theme, and I do not want to build it around a single resource pack in mind.

**Comment by ardissaps** [comment]
> Stoneborn is an interesting resourcepack. I do not want to base the entire mod around a medieval theme, and I do not want to build it around a single resource pack in mind.

I see it is ok, look like as time going MythicMetal already make some armor looks unique instead of just change color using same model (I believe the art would be improved eventually). Thank you very much!
