### ISSUE TITLE
OWO Lib Problem

### ISSUE THREAD

**Issue by ardissaps** [Noaaan/MythicMetals#83]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'oωo' (owo) 0.7.2-no-cme+1.18, mod 'oωo-sentinel' (owo-sentinel) 0.6.0+1.18 and mod 'oωo-sentinel' (owo-sentinel) 0.7.3-pre9+1.18 with mod 'oωo' (owo), version 0.7.2 or later.
Unmet dependency listing:
	 - Mod 'Mythic Metals' (mythicmetals) 0.14.0 requires version 0.7.2 or later of mod 'oωo' (owo), which can't be loaded due to other constraints!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ardissaps** [comment]
I use OWO lates for modringht for 1.18.2

**Comment by ardissaps** [comment]
![image](https://user-images.githubusercontent.com/82106625/176566332-23051dfb-702b-4b82-b0da-a2073d93a736.png)

**Comment by ardissaps** [comment]
I also tried Release version :
![image](https://user-images.githubusercontent.com/82106625/176566727-7cbf8905-29bc-4ef6-bb00-bd91584987ab.png)
But give error can't Launch : [LOG](https://paste.atlauncher.com/view/c0a09579-87f5-4e3f-80d7-e4bc846221b3)

**Comment by Balakay420** [comment]
I am also having this issue

**Comment by Noaaan** [comment]
This issue is a bit tricky, since the latest stable 1.18 version of OwO is the "No CME" version, which the fabric.mod.json can't really parse effectively. I also included a bad version of Sentinel which can't download the correct version either.
I will resolve this issue ASAP

**Comment by Noaaan** [comment]
This fix should let you run the game with the latest 1.18.2 owo, however sentinel is still broken and won't let you auto-download it.

**Comment by ardissaps** [comment]
> This fix should let you run the game with the latest 1.18.2 owo, however sentinel is still broken and won't let you auto-download it.

Can't find either on CF or modrint.
Edit : Ok i figured it out how. testing now.

**Comment by Noaaan** [comment]
You cant find them because its not released yet

**Comment by ardissaps** [comment]
> You cant find them because its not released yet

I copy and paste that code on inside the jar with winrar somewhat work. Still figuring out how to use the staff lel. :D
