### ISSUE TITLE
Incompatible with Terralith

### ISSUE THREAD

**Issue by Zekiu** [Noaaan/MythicMetals#85]
Everytime I try generating a world with Mythic Metals and Terralith installed the game crashes with "``Caused by: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / terralith:emerald_peaks]=net.minecraft.class_1959@2fe03aac}]``"

latest.log:
[latest.log](https://github.com/Noaaan/MythicMetals/files/9035580/latest.log)

latest crash report:
[crash-2022-07-04_00.17.39-server.txt](https://github.com/Noaaan/MythicMetals/files/9035581/crash-2022-07-04_00.17.39-server.txt)

**Comment by CamperSamu** [comment]
Strange, I use Terralith+ other world generation mods with mythic metals and it doesn't crash

Have you updated Fabric API?

**Comment by Zekiu** [comment]
yea, I have latest Fabric API, 0.57.0 for 1.19

**Comment by Zekiu** [comment]
Huh, seems like this issue only happens with the mod version of Terralith, datapack version works fine

**Comment by Noaaan** [comment]
Its worth noting that the datapack version of latest Terralith is versioned at 2.3.2, while the CurseForge release is at 2.3.1.
I am using biome tags for ore generation, but it never mentioms any features in the logs. Is there an oversight that has been fixed here, @Starmute ?

**Comment by ghost** [comment]
I'm also experiencing this exact issue. The mods might work at first until Emerald Peaks is generated somewhere in the world.

**Comment by Noaaan** [comment]
Talked with Starmute about it, and this is likely a bug regarding Fabrics new Conventional tags (which i use), and the explicit Terralith compat.
The convention tags automatically add vanilla tags to themselves, which is something that Terralith uses.
Because of this, Osmium is added twice to a bunch of the mountainous regions, causing a feature order cycle.

**Comment by SteveNichols5** [comment]
So not to be a pain but do we know which dev is going to be the one to fix this? Is it a Fabric fix, a Mythic Metals fix, or a Terralith fix?

**Comment by Noaaan** [comment]
This is on my side, do i will fix it
