### ISSUE TITLE
Incorrect c:ores and mythicmeats:ores tagging

### ISSUE THREAD

**Issue by goldenapple3** [Noaaan/MythicMetals#87]
With the latest version of Mythic Metals, storage blocks for ores and ingots (Raw Adamantite Block, Adamantite Block, etc) are incorrectly tagged as `c:ores` and `mythicmetals:ores`, this causes some incompatibilities like Spatial Harvesters producing Adamantite Blocks which is not an ore.

```
architectury-4.5.76-fabric.jar
cloth-config-fabric-6.2.62.jar
mythicmetals-0.14.1.jar
owo-lib-0.7.2-no-cme+1.18.jar
qsl-1.1.0-beta.19_qfapi-1.0.0-beta.22_fapi-0.56.0_mc-1.18.2.jar
RoughlyEnoughItems-8.3.501.jar
wraith-alloy-forgery-2.0.13+1.18.jar

```

**Comment by Noaaan** [comment]
> ... latest version  

*laughs in 6+ months this issue has gone unnoticed*

**Comment by goldenapple3** [comment]
I believe this started with 0.14.0 but I might be wrong
