### ISSUE TITLE
Mod crashes dedicated server when loading REI plugin

### ISSUE THREAD

**Issue by ShreksHellraiser** [Noaaan/MythicMetals#88]
When attempting to launch a server with REI and Mythical Metals installed, the server crashes.
> Caused by: java.lang.RuntimeException: Rerached side issue when loading REI plugin by Mythic Metals. Please use "rei_server", "rei_client" or "rei_common" instead.

This was using the latest 1.19 release of Mythic Metals (at the time of creation) on the latest version of Fabric.

[latest.log](https://github.com/Noaaan/MythicMetals/files/9067900/latest.log)

**Comment by ShreksHellraiser** [comment]
I've realized that REI works entirely clientside, or at least the features that I require are, so for now I've just removed it from the server pack. I'll leave the issue open for now, but if that's the intended solution then I guess it can be closed.

**Comment by Noaaan** [comment]
The solution for this is a 1 line fix in the `fabric.mod.json` as the REI entrypoint is wrong.
https://github.com/Noaaan/MythicMetals/blob/a58984239df61cd7894ade1fdb338d2d3935d00b/src/main/resources/fabric.mod.json#L26
This line should be `rei_client` instead of common.

**Comment by Noaaan** [comment]
I have made a release on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/mythicmetals/files) fixing this crash. I will keep the issue open, as I have not pushed the code yet

**Comment by ShreksHellraiser** [comment]
Thank you for the fix
