### ISSUE TITLE
[Request] Vanilla Excavator & Hammer

### ISSUE THREAD

**Issue by ardissaps** [Noaaan/MythicMetals#89]
Would you like to support these mods with MythicMetal materials please? Thank you very much.
1. [Vanilla Excavator](https://www.curseforge.com/minecraft/mc-mods/vanilla-excavators)
2. [Vanilla Hammer](https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers)

**Comment by Noaaan** [comment]
This is something I have considered, but I do not think it is something I want to add and maintain in base MM.
 It is definitely something I wish to make compat for

**Comment by Noaaan** [comment]
I was just informed there is a mod that already adds support for Hammers and Excavators with Mythic Metals. 
It is called More Hammers and Excavators: https://www.curseforge.com/minecraft/mc-mods/more-hammers-excavators

Although not every hammer seems to have textures yet, but that might simply be a matter of time.
