### ISSUE TITLE
How to use carmot staff

### ISSUE THREAD

**Issue by AssestinaR** [Noaaan/MythicMetals#90]

**Comment by Noaaan** [comment]
Carmot Staff uses right click to insert, place and extract blocks from it.  
A list of the currently supported blocks are available in the [patchnotes.](https://github.com/Noaaan/MythicMetals/blob/1.18.2/PATCHNOTES.md#0150-and-0140)

Note that this video is old, and the blocks supported and staff texture do not match up with the actual staff.

https://user-images.githubusercontent.com/4163353/179543099-1ea77f08-dd02-4514-842f-b139b6f7d8de.mp4

**Comment by AssestinaR** [comment]
> 
Oh, thank you very much
