### ISSUE TITLE
About the unobtainium ore

### ISSUE THREAD

**Issue by HemelVandernacht** [Noaaan/MythicMetals#92]
What is the specific spawn rule for this ore? It seems very hard to find in my world with ver. 1.19
I have mined for 2 days on y-26 and -27, and only find one single block, does it always spawn as single or could it spawn several?
And also, does fortune enchantment world on it?

**Comment by zurgeg** [comment]
Judging by [this](https://github.com/Noaaan/MythicMetals/wiki), unobtainium is most common at about y-25

**Comment by HemelVandernacht** [comment]
> Judging by [this](https://github.com/Noaaan/MythicMetals/wiki), unobtainium is most common at about y-25

I know, I just thought that there is also a special spawn condition for this ore since the description in the advancement says "usually found deeply surrounded by deepslate"

**Comment by Noaaan** [comment]
The advancement could definitely use a bit of changing, but generally Unobtainium does not enforce any spawn specific spawn criteria.
The reason its so rare is due to it simply having a large spawn range. Before 0.13.0 there were additional mechanics that made it rare, though these have since been removed.

**Comment by HemelVandernacht** [comment]
> The advancement could definitely use a bit of changing, but generally Unobtainium does not enforce any spawn specific spawn criteria.
> The reason its so rare is due to it simply having a large spawn range. Before 0.13.0 there were additional mechanics that made it rare, though these have since been removed.

I see. I did find another one earlier, and it would appear that fortune does work on it, I guess I was unlucky the first time. BTW, does it always spawn as single?

**Comment by Noaaan** [comment]
It can actually spawn up to three ores in a vein, albeit I rarely see those. I did find one while testing Terralith compatability the other day. 
![unknown](https://user-images.githubusercontent.com/4163353/180598783-bb527e94-c0a9-4ee5-9677-792f5210f713.png)
